/**
 * Dependency Container
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Manages dependency creation and caching per domain.
 */

import type { AdapterDynamoDBClient } from "@trustkeep/adapters";
import { getDynamoClientInstance } from "../lib/dependencies/domain-dependencies.js";
import { executionContextService } from "../lib/context/execution-context.service.js";
import {
  buildBoardExportsDomainModule,
  buildBreachPlaybooksDomainModule,
  buildDataHoldingCostsDomainModule,
  buildDecisionLogsDomainModule,
  buildIdentityDomainModule,
  buildJourneysDomainModule,
  buildMonetizationGatesDomainModule,
  buildPlatformRisksDomainModule,
  buildTrustScoresDomainModule,
} from "../domains/index.js";
import type {
  BoardExportsDomainModule,
  BreachPlaybooksDomainModule,
  DataHoldingCostsDomainModule,
  DecisionLogsDomainModule,
  IdentityDomainModule,
  JourneysDomainModule,
  MonetizationGatesDomainModule,
  PlatformRisksDomainModule,
  TrustScoresDomainModule,
} from "../domains/index.js";

class DependencyContainer {
  private readonly dynamoClient: AdapterDynamoDBClient;

  private boardExportsModule: BoardExportsDomainModule | null = null;
  private breachPlaybooksModule: BreachPlaybooksDomainModule | null = null;
  private dataHoldingCostsModule: DataHoldingCostsDomainModule | null = null;
  private decisionLogsModule: DecisionLogsDomainModule | null = null;
  private identityModule: IdentityDomainModule | null = null;
  private journeysModule: JourneysDomainModule | null = null;
  private monetizationGatesModule: MonetizationGatesDomainModule | null = null;
  private platformRisksModule: PlatformRisksDomainModule | null = null;
  private trustScoresModule: TrustScoresDomainModule | null = null;

  constructor(dynamoClient: AdapterDynamoDBClient) {
    this.dynamoClient = dynamoClient;
  }

  /**
   * Get board-exports domain module
   */
  getBoardExportsDependencies(): BoardExportsDomainModule {
    if (!this.boardExportsModule) {
      this.boardExportsModule = buildBoardExportsDomainModule(this.dynamoClient);
    }
    return this.boardExportsModule;
  }

  /**
   * Get breach-playbooks domain module
   */
  getBreachPlaybooksDependencies(): BreachPlaybooksDomainModule {
    if (!this.breachPlaybooksModule) {
      this.breachPlaybooksModule = buildBreachPlaybooksDomainModule(this.dynamoClient);
    }
    return this.breachPlaybooksModule;
  }

  /**
   * Get data-holding-costs domain module
   */
  getDataHoldingCostsDependencies(): DataHoldingCostsDomainModule {
    if (!this.dataHoldingCostsModule) {
      this.dataHoldingCostsModule = buildDataHoldingCostsDomainModule(this.dynamoClient);
    }
    return this.dataHoldingCostsModule;
  }

  /**
   * Get decision-logs domain module
   */
  getDecisionLogsDependencies(): DecisionLogsDomainModule {
    if (!this.decisionLogsModule) {
      this.decisionLogsModule = buildDecisionLogsDomainModule(this.dynamoClient);
    }
    return this.decisionLogsModule;
  }

  /**
   * Get identity domain module
   */
  getIdentityDependencies(): IdentityDomainModule {
    if (!this.identityModule) {
      this.identityModule = buildIdentityDomainModule(this.dynamoClient);
    }
    return this.identityModule;
  }

  /**
   * Get journeys domain module
   */
  getJourneysDependencies(): JourneysDomainModule {
    if (!this.journeysModule) {
      this.journeysModule = buildJourneysDomainModule(this.dynamoClient);
    }
    return this.journeysModule;
  }

  /**
   * Get monetization-gates domain module
   */
  getMonetizationGatesDependencies(): MonetizationGatesDomainModule {
    if (!this.monetizationGatesModule) {
      this.monetizationGatesModule = buildMonetizationGatesDomainModule(this.dynamoClient);
    }
    return this.monetizationGatesModule;
  }

  /**
   * Get platform-risks domain module
   */
  getPlatformRisksDependencies(): PlatformRisksDomainModule {
    if (!this.platformRisksModule) {
      this.platformRisksModule = buildPlatformRisksDomainModule(this.dynamoClient);
    }
    return this.platformRisksModule;
  }

  /**
   * Get trust-scores domain module
   */
  getTrustScoresDependencies(): TrustScoresDomainModule {
    if (!this.trustScoresModule) {
      this.trustScoresModule = buildTrustScoresDomainModule(this.dynamoClient);
    }
    return this.trustScoresModule;
  }

  clearBoardExportsDependencies(): void { this.boardExportsModule = null; }
  clearBreachPlaybooksDependencies(): void { this.breachPlaybooksModule = null; }
  clearDataHoldingCostsDependencies(): void { this.dataHoldingCostsModule = null; }
  clearDecisionLogsDependencies(): void { this.decisionLogsModule = null; }
  clearIdentityDependencies(): void { this.identityModule = null; }
  clearJourneysDependencies(): void { this.journeysModule = null; }
  clearMonetizationGatesDependencies(): void { this.monetizationGatesModule = null; }
  clearPlatformRisksDependencies(): void { this.platformRisksModule = null; }
  clearTrustScoresDependencies(): void { this.trustScoresModule = null; }

  getBoardExportsDependenciesForRequest(): BoardExportsDomainModule {
    return this.getBoardExportsDependencies();
  }

  getBreachPlaybooksDependenciesForRequest(): BreachPlaybooksDomainModule {
    return this.getBreachPlaybooksDependencies();
  }

  getDataHoldingCostsDependenciesForRequest(): DataHoldingCostsDomainModule {
    return this.getDataHoldingCostsDependencies();
  }

  getDecisionLogsDependenciesForRequest(): DecisionLogsDomainModule {
    return this.getDecisionLogsDependencies();
  }

  getIdentityDependenciesForRequest(): IdentityDomainModule {
    return this.getIdentityDependencies();
  }

  getJourneysDependenciesForRequest(): JourneysDomainModule {
    return this.getJourneysDependencies();
  }

  getMonetizationGatesDependenciesForRequest(): MonetizationGatesDomainModule {
    return this.getMonetizationGatesDependencies();
  }

  getPlatformRisksDependenciesForRequest(): PlatformRisksDomainModule {
    return this.getPlatformRisksDependencies();
  }

  getTrustScoresDependenciesForRequest(): TrustScoresDomainModule {
    return this.getTrustScoresDependencies();
  }

  /**
   * Clear all caches
   */
  clearAllCaches(): void {
    this.boardExportsModule = null;
    this.breachPlaybooksModule = null;
    this.dataHoldingCostsModule = null;
    this.decisionLogsModule = null;
    this.identityModule = null;
    this.journeysModule = null;
    this.monetizationGatesModule = null;
    this.platformRisksModule = null;
    this.trustScoresModule = null;
  }
}

let dependencyContainerInstance: DependencyContainer | null = null;

export function getDependencyContainer(): DependencyContainer {
  if (!dependencyContainerInstance) {
    const dynamoClient = getDynamoClientInstance();
    dependencyContainerInstance = new DependencyContainer(dynamoClient);
  }
  return dependencyContainerInstance;
}
