/**
 * DecisionLog DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decision-logs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DecisionLog DTOs
 *
 * DDD: Application DTOs for DecisionLog use cases.
 */

import type { CreateDecisionLogRequestInput, GetDecisionLogParams, ListDecisionLogsParams } from "@trustkeep/core/decision-logs/types";

export type ListDecisionLogsInput = ListDecisionLogsParams;

export type CreateDecisionLogInput = CreateDecisionLogRequestInput;

export type GetDecisionLogInput = GetDecisionLogParams;

export type ListDecisionLogsOutput = {};

export type CreateDecisionLogOutput = {};

export type GetDecisionLogOutput = {};
