/**
 * TrustScoresComputeRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust-scores
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TrustScoresComputeRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements TrustScoresComputeRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  TrustScoresComputeRepository,
} from "@trustkeep/services/trust-scores";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { TrustScoresComputeRepositoryDdb } from "./trust-scores-compute-repository.ddb.js";

/**
 * TrustScoresComputeRepositoryAdapter
 *
 * Implements TrustScoresComputeRepository port for infrastructure layer.
 */
export class TrustScoresComputeRepositoryAdapter implements TrustScoresComputeRepository {
  private readonly ddb: TrustScoresComputeRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new TrustScoresComputeRepositoryDdb(this.dynamoClient);
  }

  async computeTrustScore(input: Parameters<TrustScoresComputeRepository['computeTrustScore']>[0]): Promise<Awaited<ReturnType<TrustScoresComputeRepository['computeTrustScore']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.computeTrustScore(input);
  }
}
