/**
 * TrustDeltum DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breach-playbooks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TrustDeltum DTOs
 *
 * DDD: Application DTOs for TrustDeltum use cases.
 */

import type { RecordPlaybookTrustDeltaParams, RecordPlaybookTrustDeltaRequestInput } from "@trustkeep/core/breach-playbooks/types";

export type RecordPlaybookTrustDeltaInput = RecordPlaybookTrustDeltaParams & RecordPlaybookTrustDeltaRequestInput;

export type RecordPlaybookTrustDeltaOutput = {};
