/**
 * BoardExport DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: board-exports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BoardExport DTOs
 *
 * DDD: Application DTOs for BoardExport use cases.
 */

import type { CreateBoardExportRequestInput, GetBoardExportParams, ListBoardExportsParams } from "@trustkeep/core/board-exports/types";

export type ListBoardExportsInput = ListBoardExportsParams;

export type CreateBoardExportInput = CreateBoardExportRequestInput;

export type GetBoardExportInput = GetBoardExportParams;

export type ListBoardExportsOutput = {};

export type CreateBoardExportOutput = {};

export type GetBoardExportOutput = {};
