/**
 * BoardExport Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: board-exports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/board-exports.openapi.types.js";
import { schemas } from "../schemas/board-exports.schemas.js";

/**
 * Entity: BoardExportEntity
 * Description: Represents the BoardExport domain model.
 * Source: schemas.BoardExport
 * Type: Domain Entity (API)
 */
export const BoardExportEntitySchema = schemas.BoardExport;
export type BoardExportEntity = components["schemas"]["BoardExport"];
