/**
 * Journeys DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: journeys
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Journeys Domain Module - Composition root
 *
 * DDD: Composition root for journeys domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  JourneyRepositoryAdapter,
} from "@trustkeep/adapters/journeys";
import { getIdGeneratorService } from "@trustkeep/adapters";
import type { AdapterDynamoDBClient } from "@trustkeep/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateJourney,
  ExecuteGetJourney,
  ExecuteListJourneys,
  ExecuteUpdateJourney,
} from "@trustkeep/services/journeys/usecases";
// Ports (interfaces)
import type {
  JourneyRepository,
} from "@trustkeep/services/journeys/ports";

export interface JourneysDomainModule {
  repos: {
    journeys: JourneyRepository;
  };
  useCases: {
    journeys: {
      create: ExecuteCreateJourney;
      get: ExecuteGetJourney;
      list: ExecuteListJourneys;
      update: ExecuteUpdateJourney;
    };
  };
}

export function buildJourneysDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): JourneysDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      journeys?: JourneyRepository;
    } = {};

    obj.journeys = new JourneyRepositoryAdapter(dynamoClient);
    return {
      journeys: obj.journeys!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    journeys: {
      create: new ExecuteCreateJourney(executionContext, idGenerator, repos.journeys),
      get: new ExecuteGetJourney(executionContext, idGenerator, repos.journeys),
      list: new ExecuteListJourneys(executionContext, idGenerator, repos.journeys),
      update: new ExecuteUpdateJourney(executionContext, idGenerator, repos.journeys),
    },
  };
  return { repos, useCases: useCases as JourneysDomainModule["useCases"] };
}
