/**
 * Journey Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: journeys
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/journeys.openapi.types.js";
import { schemas } from "../schemas/journeys.schemas.js";

/**
 * Entity: JourneyEntity
 * Description: Represents the Journey domain model.
 * Source: schemas.Journey
 * Type: Domain Entity (API)
 */
export const JourneyEntitySchema = schemas.Journey;
export type JourneyEntity = components["schemas"]["Journey"];
