/**
 * PlatformRisks DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: platform-risks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PlatformRisks Domain Module - Composition root
 *
 * DDD: Composition root for platform-risks domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  PlatformRiskRepositoryAdapter,
} from "@trustkeep/adapters/platform-risks";
import { getIdGeneratorService } from "@trustkeep/adapters";
import type { AdapterDynamoDBClient } from "@trustkeep/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreatePlatformRisk,
  ExecuteGetPlatformRisk,
  ExecuteListPlatformRisks,
  ExecuteUpdatePlatformRisk,
} from "@trustkeep/services/platform-risks/usecases";
// Ports (interfaces)
import type {
  PlatformRiskRepository,
} from "@trustkeep/services/platform-risks/ports";

export interface PlatformRisksDomainModule {
  repos: {
    platformRisks: PlatformRiskRepository;
  };
  useCases: {
    platformRisks: {
      create: ExecuteCreatePlatformRisk;
      get: ExecuteGetPlatformRisk;
      list: ExecuteListPlatformRisks;
      update: ExecuteUpdatePlatformRisk;
    };
  };
}

export function buildPlatformRisksDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): PlatformRisksDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      platformRisks?: PlatformRiskRepository;
    } = {};

    obj.platformRisks = new PlatformRiskRepositoryAdapter(dynamoClient);
    return {
      platformRisks: obj.platformRisks!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    platformRisks: {
      create: new ExecuteCreatePlatformRisk(executionContext, idGenerator, repos.platformRisks),
      get: new ExecuteGetPlatformRisk(executionContext, idGenerator, repos.platformRisks),
      list: new ExecuteListPlatformRisks(executionContext, idGenerator, repos.platformRisks),
      update: new ExecuteUpdatePlatformRisk(executionContext, idGenerator, repos.platformRisks),
    },
  };
  return { repos, useCases: useCases as PlatformRisksDomainModule["useCases"] };
}
