/**
 * ExecuteGetMonetizationProposal - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monetization-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetMonetizationProposal Use Case
 *
 * DDD: Application use case for get MonetizationProposal.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetMonetizationProposalInput, GetMonetizationProposalOutput } from "../dto/monetization-proposal.dto";
import type { ExecutionContextService, IdGeneratorService } from "@trustkeep/services/_shared/index.js";
import type { MonetizationProposalRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetMonetizationProposal {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly monetizationProposal: MonetizationProposalRepository
  ) {}

  async execute(input: GetMonetizationProposalInput): Promise<GetMonetizationProposalOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.mnzId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).proposalId) {
      throw new ValidationError("proposalId is required");
    }
    const proposalId = (input as any).proposalId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.monetizationProposal.getMonetizationProposal({ proposalId: proposalId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${proposalId}`);
    }

    return entity as GetMonetizationProposalOutput;
  }
}
