/**
 * DataHoldingCostRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: data-holding-costs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DataHoldingCostRepository Port
 *
 * DDD: Application port for dataholdingcostrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetDataHoldingCostInput, GetDataHoldingCostOutput, ListDataHoldingCostsInput, ListDataHoldingCostsOutput, UpsertDataHoldingCostInput, UpsertDataHoldingCostOutput } from "../dto/data-holding-cost.dto";
export interface DataHoldingCostRepository {
  listDataHoldingCosts(input: ListDataHoldingCostsInput): Promise<ListDataHoldingCostsOutput>;
  upsertDataHoldingCost(input: UpsertDataHoldingCostInput): Promise<UpsertDataHoldingCostOutput>;
  getDataHoldingCost(input: GetDataHoldingCostInput): Promise<GetDataHoldingCostOutput>;
}

export type { GetDataHoldingCostInput, GetDataHoldingCostOutput, ListDataHoldingCostsInput, ListDataHoldingCostsOutput, UpsertDataHoldingCostInput, UpsertDataHoldingCostOutput } from "../dto/data-holding-cost.dto";
