/**
 * PlatformRisk DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: platform-risks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PlatformRisk DTOs
 *
 * DDD: Application DTOs for PlatformRisk use cases.
 */

import type { CreatePlatformRiskRequestInput, GetPlatformRiskParams, ListPlatformRisksParams, UpdatePlatformRiskParams, UpdatePlatformRiskRequestInput } from "@trustkeep/core/platform-risks/types";

export type ListPlatformRisksInput = ListPlatformRisksParams;

export type CreatePlatformRiskInput = CreatePlatformRiskRequestInput;

export type GetPlatformRiskInput = GetPlatformRiskParams;

export type UpdatePlatformRiskInput = UpdatePlatformRiskParams & UpdatePlatformRiskRequestInput;

export type ListPlatformRisksOutput = {};

export type CreatePlatformRiskOutput = {};

export type GetPlatformRiskOutput = {};

export type UpdatePlatformRiskOutput = {};
