/**
 * ListTrustScore DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust-scores
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListTrustScoresParams } from "@trustkeep/core/trust-scores";

export function createListTrustScoreRequest(overrides: Partial<ListTrustScoresParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
