/**
 * PlatformRiskRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: platform-risks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PlatformRiskRepository Port
 *
 * DDD: Application port for platformriskrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreatePlatformRiskInput, CreatePlatformRiskOutput, GetPlatformRiskInput, GetPlatformRiskOutput, ListPlatformRisksInput, ListPlatformRisksOutput, UpdatePlatformRiskInput, UpdatePlatformRiskOutput } from "../dto/platform-risk.dto";
export interface PlatformRiskRepository {
  listPlatformRisks(input: ListPlatformRisksInput): Promise<ListPlatformRisksOutput>;
  createPlatformRisk(input: CreatePlatformRiskInput): Promise<CreatePlatformRiskOutput>;
  getPlatformRisk(input: GetPlatformRiskInput): Promise<GetPlatformRiskOutput>;
  updatePlatformRisk(input: UpdatePlatformRiskInput): Promise<UpdatePlatformRiskOutput>;
}

export type { CreatePlatformRiskInput, CreatePlatformRiskOutput, GetPlatformRiskInput, GetPlatformRiskOutput, ListPlatformRisksInput, ListPlatformRisksOutput, UpdatePlatformRiskInput, UpdatePlatformRiskOutput } from "../dto/platform-risk.dto";
