/**
 * Journey Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: journeys
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { JourneyEntity } from "@trustkeep/core/journeys/models/index.js";
import { journeysSchemas } from "@trustkeep/core/journeys";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "jny";

export function createJourney(overrides: Partial<JourneyEntity> = {}) {
  const raw = {
    id: overrides.id ?? `jny_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    journeyKey: overrides.journeyKey ?? "acquire",
    name: overrides.name ?? faker.person.fullName(),
    status: overrides.status ?? "draft",
    trustThreshold: overrides.trustThreshold ?? faker.number.int(),
    ...overrides,
  };

  return journeysSchemas.Journey.parse(raw);
}

export function journeyBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createJourney(overrides));
}
