/**
 * ExecuteUpsertDataHoldingCost - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: data-holding-costs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpsertDataHoldingCost Use Case
 *
 * DDD: Application use case for get DataHoldingCost.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpsertDataHoldingCostInput, UpsertDataHoldingCostOutput } from "../dto/data-holding-cost.dto";
import type { ExecutionContextService, IdGeneratorService } from "@trustkeep/services/_shared/index.js";
import type { DataHoldingCostRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecuteUpsertDataHoldingCost {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly dataHoldingCost: DataHoldingCostRepository
  ) {}

  async execute(input: UpsertDataHoldingCostInput): Promise<UpsertDataHoldingCostOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dhcId();

    // All field names extracted from OpenAPI spec: annualCostPerRecord, burnDownTargetRecords, cleansedRecords, currency, datasetName, inactiveRecords
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.dataHoldingCost.upsertDataHoldingCost({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as UpsertDataHoldingCostOutput;
  }
}
