/**
 * ExecuteGetDataHoldingCost - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: data-holding-costs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetDataHoldingCost Use Case
 *
 * DDD: Application use case for get DataHoldingCost.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetDataHoldingCostInput, GetDataHoldingCostOutput } from "../dto/data-holding-cost.dto";
import type { ExecutionContextService, IdGeneratorService } from "@trustkeep/services/_shared/index.js";
import type { DataHoldingCostRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetDataHoldingCost {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly dataHoldingCost: DataHoldingCostRepository
  ) {}

  async execute(input: GetDataHoldingCostInput): Promise<GetDataHoldingCostOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dhcId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).costId) {
      throw new ValidationError("costId is required");
    }
    const costId = (input as any).costId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.dataHoldingCost.getDataHoldingCost({ costId: costId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${costId}`);
    }

    return entity as GetDataHoldingCostOutput;
  }
}
