/**
 * Routes for BoardExport
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: board-exports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createBoardExport, getBoardExport, listBoardExports } from "../handlers/board-export.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function boardExportRoutes(fastify: FastifyInstance) {
  // POST /v1/board-exports (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/board-exports",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getBoardExportsDependenciesForRequest();
        await createBoardExport(request, reply, deps);
      });
    }
  );


  // GET /v1/board-exports (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/board-exports",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getBoardExportsDependenciesForRequest();
        await listBoardExports(request, reply, deps);
      });
    }
  );


  // GET /v1/board-exports/{exportId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/board-exports/:exportId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { exportId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getBoardExportsDependenciesForRequest();
        await getBoardExport(request, reply, deps);
      });
    }
  );


}
