/**
 * DecisionLog Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decision-logs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/decision-logs.openapi.types.js";
import { schemas } from "../schemas/decision-logs.schemas.js";

/**
 * Entity: DecisionLogEntity
 * Description: Represents the DecisionLog domain model.
 * Source: schemas.DecisionLog
 * Type: Domain Entity (API)
 */
export const DecisionLogEntitySchema = schemas.DecisionLog;
export type DecisionLogEntity = components["schemas"]["DecisionLog"];
