/**
 * TrustScore DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust-scores
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TrustScore DTOs
 *
 * DDD: Application DTOs for TrustScore use cases.
 */

import type { GetTrustScoreParams, ListTrustScoresParams } from "@trustkeep/core/trust-scores/types";

export type ListTrustScoresInput = ListTrustScoresParams;

export type GetTrustScoreInput = GetTrustScoreParams;

export type ListTrustScoresOutput = {};

export type GetTrustScoreOutput = {};
