/**
 * PlatformRiskRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: platform-risks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PlatformRiskRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements PlatformRiskRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  PlatformRiskRepository,
} from "@trustkeep/services/platform-risks";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { PlatformRiskRepositoryDdb } from "./platform-risk-repository.ddb.js";

/**
 * PlatformRiskRepositoryAdapter
 *
 * Implements PlatformRiskRepository port for infrastructure layer.
 */
export class PlatformRiskRepositoryAdapter implements PlatformRiskRepository {
  private readonly ddb: PlatformRiskRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new PlatformRiskRepositoryDdb(this.dynamoClient);
  }

  async listPlatformRisks(input: Parameters<PlatformRiskRepository['listPlatformRisks']>[0]): Promise<Awaited<ReturnType<PlatformRiskRepository['listPlatformRisks']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listPlatformRisks(input);
  }

  async createPlatformRisk(input: Parameters<PlatformRiskRepository['createPlatformRisk']>[0]): Promise<Awaited<ReturnType<PlatformRiskRepository['createPlatformRisk']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createPlatformRisk(input);
  }

  async getPlatformRisk(input: Parameters<PlatformRiskRepository['getPlatformRisk']>[0]): Promise<Awaited<ReturnType<PlatformRiskRepository['getPlatformRisk']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getPlatformRisk(input);
  }

  async updatePlatformRisk(input: Parameters<PlatformRiskRepository['updatePlatformRisk']>[0]): Promise<Awaited<ReturnType<PlatformRiskRepository['updatePlatformRisk']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updatePlatformRisk(input);
  }
}
