/**
 * GetBoardExport handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: board-exports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getBoardExport } from "@trustkeep/api-server/domains/board-exports/handlers";
import type { BoardExportsDDDDependencies } from "@trustkeep/api-server/domains/board-exports";
import { createBoardExport as createBoardExportEntity } from "@trustkeep/factories/board-exports";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@trustkeep/tests/shared";
import { BOARDEXPORTS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetBoardExport", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: BoardExportsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<BoardExportsDDDDependencies>(
      BOARDEXPORTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createBoardExportEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetBoardExport, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { exportId: entity.id };

    await getBoardExport(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetBoardExport.execute).toHaveBeenCalledWith(expect.objectContaining({ exportId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { exportId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetBoardExport, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getBoardExport(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
