/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust-scores
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { trustScoreRoutes } from "./trust-score.routes.js";
export { trustScoresComputeRoutes } from "./trust-scores-compute.routes.js";
