/**
 * Routes for TrustScore
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust-scores
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getTrustScore, listTrustScores } from "../handlers/trust-score.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function trustScoreRoutes(fastify: FastifyInstance) {
  // GET /v1/trust-scores (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/trust-scores",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getTrustScoresDependenciesForRequest();
        await listTrustScores(request, reply, deps);
      });
    }
  );


  // GET /v1/trust-scores/{trustScoreId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/trust-scores/:trustScoreId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { trustScoreId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getTrustScoresDependenciesForRequest();
        await getTrustScore(request, reply, deps);
      });
    }
  );


}
