/**
 * MonetizationGates DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monetization-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * MonetizationGates Domain Module - Composition root
 *
 * DDD: Composition root for monetization-gates domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  GateDecisionRepositoryAdapter,
  MonetizationProposalRepositoryAdapter,
} from "@trustkeep/adapters/monetization-gates";
import { getIdGeneratorService } from "@trustkeep/adapters";
import type { AdapterDynamoDBClient } from "@trustkeep/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteDecideMonetizationGate,
  ExecuteGetMonetizationProposal,
  ExecuteListMonetizationProposals,
  ExecuteSubmitMonetizationProposal,
} from "@trustkeep/services/monetization-gates/usecases";
// Ports (interfaces)
import type {
  GateDecisionRepository,
  MonetizationProposalRepository,
} from "@trustkeep/services/monetization-gates/ports";

export interface MonetizationGatesDomainModule {
  repos: {
    gateDecisions: GateDecisionRepository;
    monetizationProposals: MonetizationProposalRepository;
  };
  useCases: {
    gateDecisions: {
      get: ExecuteDecideMonetizationGate;
    };
    monetizationProposals: {
      create: ExecuteSubmitMonetizationProposal;
      get: ExecuteGetMonetizationProposal;
      list: ExecuteListMonetizationProposals;
    };
  };
}

export function buildMonetizationGatesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): MonetizationGatesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      gateDecisions?: GateDecisionRepository;
      monetizationProposals?: MonetizationProposalRepository;
    } = {};

    obj.gateDecisions = new GateDecisionRepositoryAdapter(dynamoClient);
    obj.monetizationProposals = new MonetizationProposalRepositoryAdapter(dynamoClient);
    return {
      gateDecisions: obj.gateDecisions!,
      monetizationProposals: obj.monetizationProposals!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    gateDecisions: {
      get: new ExecuteDecideMonetizationGate(executionContext, idGenerator, repos.gateDecisions),
    },
    monetizationProposals: {
      create: new ExecuteSubmitMonetizationProposal(executionContext, idGenerator, repos.monetizationProposals),
      get: new ExecuteGetMonetizationProposal(executionContext, idGenerator, repos.monetizationProposals),
      list: new ExecuteListMonetizationProposals(executionContext, idGenerator, repos.monetizationProposals),
    },
  };
  return { repos, useCases: useCases as MonetizationGatesDomainModule["useCases"] };
}
