/**
 * Handlers for BoardExport
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: board-exports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { BoardExportsDomainModule } from "../dependencies/board-exports-ddd.dependencies.js";
import type { CreateBoardExportInput, GetBoardExportInput, ListBoardExportsInput } from "@trustkeep/services/board-exports";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/board-exports
 * Operation: listBoardExports
 */
export async function listBoardExports(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: BoardExportsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListBoardExportsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.boardExports.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/board-exports
 * Operation: createBoardExport
 */
export async function createBoardExport(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: BoardExportsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateBoardExportInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.boardExports.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/board-exports/{exportId}
 * Operation: getBoardExport
 */
export async function getBoardExport(
  request: FastifyRequest<{ Params: { exportId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: BoardExportsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetBoardExportInput = {
    exportId: request.params.exportId,
  };
  const result = await deps.useCases.boardExports.get.execute(input);
  return reply.code(200).send(result);
}


