/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: data-holding-costs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * DataHoldingCosts Domain Use Cases
 * 
 * List of all use case names for the data-holding-costs domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const DATAHOLDINGCOSTS_USE_CASES = [
  "executeGetDataHoldingCost",
  "executeListDataHoldingCosts",
  "executeUpsertDataHoldingCost"
] as const;
