/**
 * Handlers for TrustScoresCompute
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust-scores
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { TrustScoresDomainModule } from "../dependencies/trust-scores-ddd.dependencies.js";
import type { ComputeTrustScoreInput } from "@trustkeep/services/trust-scores";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/journeys/{journeyId}/trust-scores:compute
 * Operation: computeTrustScore
 */
export async function computeTrustScore(
  request: FastifyRequest<{ Params: { journeyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: TrustScoresDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ComputeTrustScoreInput = {
    journeyId: request.params.journeyId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.computes.get.execute(input);
  return reply.code(201).send(result);
}


