/**
 * Domain routes – register all domain route modules.
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Rescans platform/api-server/src/domains and includes only domains that have
 * routes/index.ts and dependencies/{domain}-ddd.dependencies.ts.
 * Extension excludes/imports from x-codegen.api-server.extensions in OpenAPI YAML.
 */

import type { FastifyInstance } from "fastify";
import { registerDomainFromModule } from "./route-registration.js";

// Static imports so the bundle includes all domain route modules
import * as boardExportsRoutes from "../../domains/board-exports/routes/index.js";
import * as breachPlaybooksRoutes from "../../domains/breach-playbooks/routes/index.js";
import * as dataHoldingCostsRoutes from "../../domains/data-holding-costs/routes/index.js";
import * as decisionLogsRoutes from "../../domains/decision-logs/routes/index.js";
import * as identityRoutes from "../../domains/identity/routes/index.js";
import * as journeysRoutes from "../../domains/journeys/routes/index.js";
import * as monetizationGatesRoutes from "../../domains/monetization-gates/routes/index.js";
import * as platformRisksRoutes from "../../domains/platform-risks/routes/index.js";
import * as trustScoresRoutes from "../../domains/trust-scores/routes/index.js";

const DOMAIN_MODULES: Array<{
  domain: string;
  mod: Record<string, unknown>;
  exclude?: string[];
}> = [
  { domain: "board-exports", mod: boardExportsRoutes },
  { domain: "breach-playbooks", mod: breachPlaybooksRoutes },
  { domain: "data-holding-costs", mod: dataHoldingCostsRoutes },
  { domain: "decision-logs", mod: decisionLogsRoutes },
  {
    domain: "identity", mod: identityRoutes,
    exclude: ["authRoutes", "loginRoutes", "logoutRoutes", "signupRoutes", "sessionRoutes", "refreshRoutes", "tokenRoutes", "profileRoutes"],
  },
  { domain: "journeys", mod: journeysRoutes },
  { domain: "monetization-gates", mod: monetizationGatesRoutes },
  { domain: "platform-risks", mod: platformRisksRoutes },
  { domain: "trust-scores", mod: trustScoresRoutes },
];

export async function registerAllDomainRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  console.log("[DEBUG] Registering domain routes...");
  try {
    for (const { domain, mod, exclude } of DOMAIN_MODULES) {
      await registerDomainFromModule(fastify, domain, mod, exclude ?? []);
    }
    console.log("[DEBUG] ✅ All domain routes registered");
  } catch (error: unknown) {
    const err = error instanceof Error ? error : new Error(String(error));
    console.error("[DEBUG] ❌ Error registering domain routes:", err.message);
    if (err.stack) console.error(err.stack);
    throw error;
  }
}
