/**
 * System Routes - Health check and routes listing
 *
 * AUTO-GENERATED by codegen (api_server_system_routes). Do not edit by hand.
 * Domains and routeExamples are derived from discovered api-server domains and
 * each domain's OpenAPI bundled spec.
 */

import type { FastifyInstance } from "fastify";
import {
  getCoreTableName,
  getBaseTableName,
  getAnalyticsTableName,
} from "@trustkeep/adapters";
import { getRegisteredRoutes } from "./route-registry.js";

/**
 * Register system routes (health check, routes listing)
 */
export function registerSystemRoutes(fastify: FastifyInstance): void {
  // Health check (public - no auth required)
  fastify.get("/health", { config: { scope: "public" } }, async () => {
    try {
      const coreTable = getCoreTableName();
      const baseTable = getBaseTableName();
      const analyticsTable = getAnalyticsTableName();
      return {
        status: "ok",
        database: "dynamodb",
        tables: {
          core: coreTable,
          base: baseTable,
          analytics: analyticsTable,
        },
      };
    } catch (error: unknown) {
      const errorMessage =
        error instanceof Error ? error.message : String(error);
      fastify.log.warn({ error: errorMessage }, "Health check failed");
      return { status: "error", database: "disconnected", error: errorMessage };
    }
  });

  // Routes listing endpoint (public)
  fastify.get("/routes", { config: { scope: "public" } }, async () => {
    const domains = [
      "board-exports", "breach-playbooks", "data-holding-costs", "decision-logs", "identity", "journeys", "monetization-gates", "platform-risks", "trust-scores"
    ];

    const routeExamples: Record<
      string,
      Array<{ method: string; path: string; description?: string }>
    > = {
      "board-exports": [{ method: "GET", path: "/v1/board-exports" }, { method: "POST", path: "/v1/board-exports" }, { method: "GET", path: "/v1/board-exports/:exportId" }],
      "breach-playbooks": [{ method: "GET", path: "/v1/breach-incidents" }, { method: "POST", path: "/v1/breach-incidents" }, { method: "GET", path: "/v1/breach-incidents/:incidentId" }, { method: "GET", path: "/v1/breach-incidents/:incidentId/playbook-runs" }, { method: "POST", path: "/v1/breach-incidents/:incidentId/playbook-runs" }, { method: "POST", path: "/v1/playbook-runs/:runId/trust-delta" }],
      "data-holding-costs": [{ method: "GET", path: "/v1/data-holding-costs" }, { method: "POST", path: "/v1/data-holding-costs" }, { method: "GET", path: "/v1/data-holding-costs/:costId" }],
      "decision-logs": [{ method: "GET", path: "/v1/decision-logs" }, { method: "POST", path: "/v1/decision-logs" }, { method: "GET", path: "/v1/decision-logs/:decisionId" }],
      identity: [{ method: "GET", path: "/v0/tenants/me/api-keys" }, { method: "POST", path: "/v0/tenants/me/api-keys" }, { method: "GET", path: "/v0/tenants/me/api-keys/:keyId" }, { method: "DELETE", path: "/v0/tenants/me/api-keys/:keyId" }, { method: "GET", path: "/v0/tenants/me/users" }, { method: "POST", path: "/v0/tenants/me/users" }, { method: "GET", path: "/v0/tenants/me/users/:userId" }, { method: "PATCH", path: "/v0/tenants/me/users/:userId" }, { method: "POST", path: "/v0/tenants/me/users/:userId/disable" }, { method: "POST", path: "/v0/tenants/me/users/:userId/enable" }, { method: "POST", path: "/v0/auth/login" }, { method: "GET", path: "/v0/auth/me" }, { method: "PATCH", path: "/v0/auth/me" }, { method: "POST", path: "/v0/auth/refresh" }, { method: "POST", path: "/v0/auth/logout" }],
      journeys: [{ method: "GET", path: "/v1/journeys" }, { method: "POST", path: "/v1/journeys" }, { method: "GET", path: "/v1/journeys/:journeyId" }, { method: "PATCH", path: "/v1/journeys/:journeyId" }],
      "monetization-gates": [{ method: "GET", path: "/v1/monetization-proposals" }, { method: "POST", path: "/v1/monetization-proposals" }, { method: "GET", path: "/v1/monetization-proposals/:proposalId" }, { method: "POST", path: "/v1/monetization-proposals/:proposalId/gate-decision" }],
      "platform-risks": [{ method: "GET", path: "/v1/platform-risks" }, { method: "POST", path: "/v1/platform-risks" }, { method: "GET", path: "/v1/platform-risks/:riskId" }, { method: "PATCH", path: "/v1/platform-risks/:riskId" }],
      "trust-scores": [{ method: "GET", path: "/v1/trust-scores" }, { method: "POST", path: "/v1/journeys/:journeyId/trust-scores:compute" }, { method: "GET", path: "/v1/trust-scores/:trustScoreId" }],
    };

    return {
      baseUrl: "http://localhost:4000",
      routePattern: "/orgs/:orgId/{domain}/{resource}",
      authentication:
        "All routes (except /health and /routes) require JWT token in Authorization header",
      domains: domains.sort(),
      routeExamples,
      systemRoutes: [
        { method: "GET", path: "/health", description: "Health check endpoint" },
        { method: "GET", path: "/routes", description: "List available routes" },
      ],
      note: "Replace :orgId with actual organization ID. All domain routes require authentication.",
    };
  });

  // Full route list for API tester page (public)
  fastify.get("/routes/full", { config: { scope: "public" } }, async () => {
    const routes = getRegisteredRoutes();
    const byDomain: Record<
      string,
      Array<{ method: string; path: string }>
    > = {};
    const system: Array<{ method: string; path: string }> = [];
    for (const r of routes) {
      const m = r.path.match(/^\/orgs\/:orgId\/([^/]+)/);
      if (m) {
        const domain = m[1];
        if (!byDomain[domain]) byDomain[domain] = [];
        byDomain[domain].push(r);
      } else {
        system.push(r);
      }
    }
    return {
      baseUrl: "http://localhost:4000",
      total: routes.length,
      system,
      byDomain: Object.keys(byDomain)
        .sort()
        .reduce(
          (acc, k) => ({ ...acc, [k]: byDomain[k] }),
          {} as Record<string, Array<{ method: string; path: string }>>,
        ),
    };
  });
}
