/**
 * GetTrustScore handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust-scores
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getTrustScore } from "@trustkeep/api-server/domains/trust-scores/handlers";
import type { TrustScoresDDDDependencies } from "@trustkeep/api-server/domains/trust-scores";
import { createTrustScore as createTrustScoreEntity } from "@trustkeep/factories/trust-scores";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@trustkeep/tests/shared";
import { TRUSTSCORES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetTrustScore", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: TrustScoresDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<TrustScoresDDDDependencies>(
      TRUSTSCORES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createTrustScoreEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetTrustScore, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { trustScoreId: entity.id };

    await getTrustScore(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetTrustScore.execute).toHaveBeenCalledWith(expect.objectContaining({ trustScoreId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { trustScoreId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetTrustScore, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getTrustScore(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
