/**
 * Routes for MonetizationProposal
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monetization-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getMonetizationProposal, listMonetizationProposals, submitMonetizationProposal } from "../handlers/monetization-proposal.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function monetizationProposalRoutes(fastify: FastifyInstance) {
  // GET /v1/monetization-proposals (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/monetization-proposals",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getMonetizationGatesDependenciesForRequest();
        await listMonetizationProposals(request, reply, deps);
      });
    }
  );


  // POST /v1/monetization-proposals (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/monetization-proposals",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getMonetizationGatesDependenciesForRequest();
        await submitMonetizationProposal(request, reply, deps);
      });
    }
  );


  // GET /v1/monetization-proposals/{proposalId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/monetization-proposals/:proposalId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { proposalId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getMonetizationGatesDependenciesForRequest();
        await getMonetizationProposal(request, reply, deps);
      });
    }
  );


}
