/**
 * Handlers for DecisionLog
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decision-logs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { DecisionLogsDomainModule } from "../dependencies/decision-logs-ddd.dependencies.js";
import type { CreateDecisionLogInput, GetDecisionLogInput, ListDecisionLogsInput } from "@trustkeep/services/decision-logs";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/decision-logs
 * Operation: listDecisionLogs
 */
export async function listDecisionLogs(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], journeyId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: DecisionLogsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListDecisionLogsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.decisionLogs.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/decision-logs
 * Operation: createDecisionLog
 */
export async function createDecisionLog(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: DecisionLogsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateDecisionLogInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.decisionLogs.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/decision-logs/{decisionId}
 * Operation: getDecisionLog
 */
export async function getDecisionLog(
  request: FastifyRequest<{ Params: { decisionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: DecisionLogsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetDecisionLogInput = {
    decisionId: request.params.decisionId,
  };
  const result = await deps.useCases.decisionLogs.get.execute(input);
  return reply.code(200).send(result);
}


