/**
 * DataHoldingCosts DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: data-holding-costs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DataHoldingCosts Domain Module - Composition root
 *
 * DDD: Composition root for data-holding-costs domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  DataHoldingCostRepositoryAdapter,
} from "@trustkeep/adapters/data-holding-costs";
import { getIdGeneratorService } from "@trustkeep/adapters";
import type { AdapterDynamoDBClient } from "@trustkeep/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetDataHoldingCost,
  ExecuteListDataHoldingCosts,
  ExecuteUpsertDataHoldingCost,
} from "@trustkeep/services/data-holding-costs/usecases";
// Ports (interfaces)
import type {
  DataHoldingCostRepository,
} from "@trustkeep/services/data-holding-costs/ports";

export interface DataHoldingCostsDomainModule {
  repos: {
    dataHoldingCosts: DataHoldingCostRepository;
  };
  useCases: {
    dataHoldingCosts: {
      get: ExecuteGetDataHoldingCost;
      list: ExecuteListDataHoldingCosts;
    };
  };
}

export function buildDataHoldingCostsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): DataHoldingCostsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      dataHoldingCosts?: DataHoldingCostRepository;
    } = {};

    obj.dataHoldingCosts = new DataHoldingCostRepositoryAdapter(dynamoClient);
    return {
      dataHoldingCosts: obj.dataHoldingCosts!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    dataHoldingCosts: {
      get: new ExecuteGetDataHoldingCost(executionContext, idGenerator, repos.dataHoldingCosts),
      list: new ExecuteListDataHoldingCosts(executionContext, idGenerator, repos.dataHoldingCosts),
    },
  };
  return { repos, useCases: useCases as DataHoldingCostsDomainModule["useCases"] };
}
