/**
 * Repository interface for BoardExport
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: board-exports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  BoardExportEntity
} from "../models/board-export.entity.js";
import type {
  ListBoardExportsParams,
  BoardExport
} from "../types/index.js";
/**
 * BoardExportRepository Interface
 */
export interface BoardExportRepository extends CreateReadRepository<BoardExportEntity, BoardExport, string, ListBoardExportsParams> {

}
