/**
 * TrustScore Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust-scores
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { TrustScoreEntity } from "@trustkeep/core/trust-scores/models/index.js";
import { trustScoresSchemas } from "@trustkeep/core/trust-scores";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "trs";

export function createTrustScore(overrides: Partial<TrustScoreEntity> = {}) {
  const raw = {
    id: overrides.id ?? `trs_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    computedAt: overrides.computedAt ?? new Date().toISOString(),
    consent: overrides.consent ?? {
      optInRate: 0,
      revokeRate: 0,
      complaintProxyRate: 0
    },
    gateState: overrides.gateState ?? "open",
    journeyId: overrides.journeyId ?? `jny_${ulid().toLowerCase()}`,
    score: overrides.score ?? faker.number.int(),
    ...overrides,
  };

  return trustScoresSchemas.TrustScore.parse(raw);
}

export function trustScoreBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createTrustScore(overrides));
}
