/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breach-playbooks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * BreachPlaybooks Domain Use Cases
 * 
 * List of all use case names for the breach-playbooks domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const BREACHPLAYBOOKS_USE_CASES = [
  "executeGetBreachIncident",
  "executeListBreachIncidents",
  "executeListPlaybookRuns",
  "executeOpenBreachIncident",
  "executeRecordPlaybookTrustDelta",
  "executeStartPlaybookRun"
] as const;
