/**
 * BreachIncident Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breach-playbooks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { BreachIncidentEntity } from "@trustkeep/core/breach-playbooks/models/index.js";
import { breachPlaybooksSchemas } from "@trustkeep/core/breach-playbooks";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "brc";

export function createBreachIncident(overrides: Partial<BreachIncidentEntity> = {}) {
  const raw = {
    id: overrides.id ?? `brc_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    detectedAt: overrides.detectedAt ?? new Date().toISOString(),
    status: overrides.status ?? "open",
    ...overrides,
  };

  return breachPlaybooksSchemas.BreachIncident.parse(raw);
}

export function breachIncidentBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createBreachIncident(overrides));
}
