/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breach-playbooks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { breachIncidentRoutes } from "./breach-incident.routes.js";
export { playbookRunRoutes } from "./playbook-run.routes.js";
export { trustDeltumRoutes } from "./trust-deltum.routes.js";
