/**
 * DataHoldingCost Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: data-holding-costs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { DataHoldingCostEntity } from "@trustkeep/core/data-holding-costs/models/index.js";
import { dataHoldingCostsSchemas } from "@trustkeep/core/data-holding-costs";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "dhc";

export function createDataHoldingCost(overrides: Partial<DataHoldingCostEntity> = {}) {
  const raw = {
    id: overrides.id ?? `dhc_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    annualCostPerRecord: overrides.annualCostPerRecord ?? faker.number.int(),
    datasetName: overrides.datasetName ?? faker.lorem.word(),
    estimatedAnnualCost: overrides.estimatedAnnualCost ?? faker.number.int(),
    inactiveRecords: overrides.inactiveRecords ?? faker.number.int(),
    ...overrides,
  };

  return dataHoldingCostsSchemas.DataHoldingCost.parse(raw);
}

export function dataHoldingCostBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createDataHoldingCost(overrides));
}
