/**
 * DecisionLogRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decision-logs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DecisionLogRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DecisionLogRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DecisionLogRepository,
} from "@trustkeep/services/decision-logs";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DecisionLogRepositoryDdb } from "./decision-log-repository.ddb.js";

/**
 * DecisionLogRepositoryAdapter
 *
 * Implements DecisionLogRepository port for infrastructure layer.
 */
export class DecisionLogRepositoryAdapter implements DecisionLogRepository {
  private readonly ddb: DecisionLogRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DecisionLogRepositoryDdb(this.dynamoClient);
  }

  async listDecisionLogs(input: Parameters<DecisionLogRepository['listDecisionLogs']>[0]): Promise<Awaited<ReturnType<DecisionLogRepository['listDecisionLogs']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listDecisionLogs(input);
  }

  async createDecisionLog(input: Parameters<DecisionLogRepository['createDecisionLog']>[0]): Promise<Awaited<ReturnType<DecisionLogRepository['createDecisionLog']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createDecisionLog(input);
  }

  async getDecisionLog(input: Parameters<DecisionLogRepository['getDecisionLog']>[0]): Promise<Awaited<ReturnType<DecisionLogRepository['getDecisionLog']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getDecisionLog(input);
  }
}
