/**
 * PlatformRisk Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: platform-risks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/platform-risks.openapi.types.js";
import { schemas } from "../schemas/platform-risks.schemas.js";

/**
 * Entity: PlatformRiskEntity
 * Description: Represents the PlatformRisk domain model.
 * Source: schemas.PlatformRisk
 * Type: Domain Entity (API)
 */
export const PlatformRiskEntitySchema = schemas.PlatformRisk;
export type PlatformRiskEntity = components["schemas"]["PlatformRisk"];
