/**
 * BoardExportRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: board-exports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BoardExportRepository Port
 *
 * DDD: Application port for boardexportrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateBoardExportInput, CreateBoardExportOutput, GetBoardExportInput, GetBoardExportOutput, ListBoardExportsInput, ListBoardExportsOutput } from "../dto/board-export.dto";
export interface BoardExportRepository {
  listBoardExports(input: ListBoardExportsInput): Promise<ListBoardExportsOutput>;
  createBoardExport(input: CreateBoardExportInput): Promise<CreateBoardExportOutput>;
  getBoardExport(input: GetBoardExportInput): Promise<GetBoardExportOutput>;
}

export type { CreateBoardExportInput, CreateBoardExportOutput, GetBoardExportInput, GetBoardExportOutput, ListBoardExportsInput, ListBoardExportsOutput } from "../dto/board-export.dto";
