/**
 * DataHoldingCost Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: data-holding-costs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/data-holding-costs.openapi.types.js";
import { schemas } from "../schemas/data-holding-costs.schemas.js";

/**
 * Entity: DataHoldingCostEntity
 * Description: Represents the DataHoldingCost domain model.
 * Source: schemas.DataHoldingCost
 * Type: Domain Entity (API)
 */
export const DataHoldingCostEntitySchema = schemas.DataHoldingCost;
export type DataHoldingCostEntity = components["schemas"]["DataHoldingCost"];
