/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: platform-risks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @trustkeep/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@trustkeep/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@trustkeep/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@trustkeep/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@trustkeep/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@trustkeep/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _boardExports from "./board-exports/index.js";
import * as _breachPlaybooks from "./breach-playbooks/index.js";
import * as _dataHoldingCosts from "./data-holding-costs/index.js";
import * as _decisionLogs from "./decision-logs/index.js";
import * as _identity from "./identity/index.js";
import * as _journeys from "./journeys/index.js";
import * as _monetizationGates from "./monetization-gates/index.js";
import * as _platformRisks from "./platform-risks/index.js";
import * as _trustScores from "./trust-scores/index.js";

// Export as namespaces
export const _shared = __shared;
export const boardExports = _boardExports;
export const breachPlaybooks = _breachPlaybooks;
export const dataHoldingCosts = _dataHoldingCosts;
export const decisionLogs = _decisionLogs;
export const identity = _identity;
export const journeys = _journeys;
export const monetizationGates = _monetizationGates;
export const platformRisks = _platformRisks;
export const trustScores = _trustScores;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@trustkeep/core"; activity.types.*
//   - Direct exports: import * from "@trustkeep/core/activity/types/index.js"
//   - Direct exports: import * from "@trustkeep/core/activity/repositories/index.js"
//   - Direct exports: import * from "@trustkeep/core/activity/models/index.js"
//   - Direct exports: import * from "@trustkeep/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// BoardExports Service
export { schemas as BoardExportsSchemas } from "./board-exports/schemas/board-exports.schemas.js";

// BreachPlaybooks Service
export { schemas as BreachPlaybooksSchemas } from "./breach-playbooks/schemas/breach-playbooks.schemas.js";

// DataHoldingCosts Service
export { schemas as DataHoldingCostsSchemas } from "./data-holding-costs/schemas/data-holding-costs.schemas.js";

// DecisionLogs Service
export { schemas as DecisionLogsSchemas } from "./decision-logs/schemas/decision-logs.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// Journeys Service
export { schemas as JourneysSchemas } from "./journeys/schemas/journeys.schemas.js";

// MonetizationGates Service
export { schemas as MonetizationGatesSchemas } from "./monetization-gates/schemas/monetization-gates.schemas.js";

// PlatformRisks Service
export { schemas as PlatformRisksSchemas } from "./platform-risks/schemas/platform-risks.schemas.js";

// TrustScores Service
export { schemas as TrustScoresSchemas } from "./trust-scores/schemas/trust-scores.schemas.js";

