/**
 * ExecuteOpenBreachIncident - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breach-playbooks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteOpenBreachIncident Use Case
 *
 * DDD: Application use case for get BreachIncident.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { OpenBreachIncidentInput, OpenBreachIncidentOutput } from "../dto/breach-incident.dto";
import type { ExecutionContextService, IdGeneratorService } from "@trustkeep/services/_shared/index.js";
import type { BreachIncidentRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecuteOpenBreachIncident {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly breachIncident: BreachIncidentRepository
  ) {}

  async execute(input: OpenBreachIncidentInput): Promise<OpenBreachIncidentOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.brcId();

    // All field names extracted from OpenAPI spec: detectedAt, summary
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.breachIncident.openBreachIncident({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as OpenBreachIncidentOutput;
  }
}
