/**
 * ExecuteListPlaybookRuns - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breach-playbooks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListPlaybookRuns Use Case
 *
 * DDD: Application use case for list PlaybookRun.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListPlaybookRunsInput, ListPlaybookRunsOutput } from "../dto/playbook-run.dto";
import type { ExecutionContextService, IdGeneratorService } from "@trustkeep/services/_shared/index.js";
import type { PlaybookRunRepository } from "../ports";

export class ExecuteListPlaybookRuns {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly playbookRun: PlaybookRunRepository
  ) {}

  async execute(input: ListPlaybookRunsInput): Promise<ListPlaybookRunsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.brcId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.playbookRun.listPlaybookRuns({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListPlaybookRunsOutput;
  }
}
