/**
 * ExecuteStartPlaybookRun - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breach-playbooks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteStartPlaybookRun Use Case
 *
 * DDD: Application use case for create PlaybookRun.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { StartPlaybookRunInput, StartPlaybookRunOutput } from "../dto/playbook-run.dto";
import type { ExecutionContextService, IdGeneratorService } from "@trustkeep/services/_shared/index.js";
import type { PlaybookRunRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteStartPlaybookRun {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly playbookRun: PlaybookRunRepository
  ) {}

  async execute(input: StartPlaybookRunInput): Promise<StartPlaybookRunOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.brcId();

    // All field names extracted from OpenAPI spec: playbookKey
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.playbookKey) {
      throw new ValidationError("playbookKey is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (breach-playbooks domain)
    const entityId = this.idGenerator.brcId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.playbookRun.startPlaybookRun({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as StartPlaybookRunOutput;
  }
}
