/**
 * Handlers for BreachIncident
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breach-playbooks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { BreachPlaybooksDomainModule } from "../dependencies/breach-playbooks-ddd.dependencies.js";
import type { GetBreachIncidentInput, ListBreachIncidentsInput, OpenBreachIncidentInput } from "@trustkeep/services/breach-playbooks";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/breach-incidents
 * Operation: listBreachIncidents
 */
export async function listBreachIncidents(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: BreachPlaybooksDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListBreachIncidentsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.breachIncidents.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/breach-incidents
 * Operation: openBreachIncident
 */
export async function openBreachIncident(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: BreachPlaybooksDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: OpenBreachIncidentInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.breachIncidents.get.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/breach-incidents/{incidentId}
 * Operation: getBreachIncident
 */
export async function getBreachIncident(
  request: FastifyRequest<{ Params: { incidentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: BreachPlaybooksDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetBreachIncidentInput = {
    incidentId: request.params.incidentId,
  };
  const result = await deps.useCases.breachIncidents.get.execute(input);
  return reply.code(200).send(result);
}


