/**
 * Handlers for PlaybookRun
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breach-playbooks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { BreachPlaybooksDomainModule } from "../dependencies/breach-playbooks-ddd.dependencies.js";
import type { ListPlaybookRunsInput, StartPlaybookRunInput } from "@trustkeep/services/breach-playbooks";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/breach-incidents/{incidentId}/playbook-runs
 * Operation: listPlaybookRuns
 */
export async function listPlaybookRuns(
  request: FastifyRequest<{ Params: { incidentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: BreachPlaybooksDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListPlaybookRunsInput = {
    incidentId: request.params.incidentId,
  };
  const result = await deps.useCases.playbookRuns.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/breach-incidents/{incidentId}/playbook-runs
 * Operation: startPlaybookRun
 */
export async function startPlaybookRun(
  request: FastifyRequest<{ Params: { incidentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: BreachPlaybooksDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: StartPlaybookRunInput = {
    incidentId: request.params.incidentId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.playbookRuns.create.execute(input);
  return reply.code(201).send(result);
}


