/**
 * Handlers for TrustDeltum
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breach-playbooks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { BreachPlaybooksDomainModule } from "../dependencies/breach-playbooks-ddd.dependencies.js";
import type { RecordPlaybookTrustDeltaInput } from "@trustkeep/services/breach-playbooks";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/playbook-runs/{runId}/trust-delta
 * Operation: recordPlaybookTrustDelta
 */
export async function recordPlaybookTrustDelta(
  request: FastifyRequest<{ Params: { runId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: BreachPlaybooksDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RecordPlaybookTrustDeltaInput = {
    runId: request.params.runId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.trustDelta.get.execute(input);
  return reply.code(200).send(result);
}


