/**
 * BoardExports DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: board-exports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BoardExports Domain Module - Composition root
 *
 * DDD: Composition root for board-exports domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  BoardExportRepositoryAdapter,
} from "@trustkeep/adapters/board-exports";
import { getIdGeneratorService } from "@trustkeep/adapters";
import type { AdapterDynamoDBClient } from "@trustkeep/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateBoardExport,
  ExecuteGetBoardExport,
  ExecuteListBoardExports,
} from "@trustkeep/services/board-exports/usecases";
// Ports (interfaces)
import type {
  BoardExportRepository,
} from "@trustkeep/services/board-exports/ports";

export interface BoardExportsDomainModule {
  repos: {
    boardExports: BoardExportRepository;
  };
  useCases: {
    boardExports: {
      create: ExecuteCreateBoardExport;
      get: ExecuteGetBoardExport;
      list: ExecuteListBoardExports;
    };
  };
}

export function buildBoardExportsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): BoardExportsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      boardExports?: BoardExportRepository;
    } = {};

    obj.boardExports = new BoardExportRepositoryAdapter(dynamoClient);
    return {
      boardExports: obj.boardExports!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    boardExports: {
      create: new ExecuteCreateBoardExport(executionContext, idGenerator, repos.boardExports),
      get: new ExecuteGetBoardExport(executionContext, idGenerator, repos.boardExports),
      list: new ExecuteListBoardExports(executionContext, idGenerator, repos.boardExports),
    },
  };
  return { repos, useCases: useCases as BoardExportsDomainModule["useCases"] };
}
