/**
 * Repository interface for DataHoldingCost
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: data-holding-costs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  DataHoldingCostEntity
} from "../models/data-holding-cost.entity.js";
import type {
  ListDataHoldingCostsParams,
  DataHoldingCost
} from "../types/index.js";
/**
 * DataHoldingCostRepository Interface
 */
export interface DataHoldingCostRepository extends CreateReadRepository<DataHoldingCostEntity, DataHoldingCost, string, ListDataHoldingCostsParams> {

}
