/**
 * DataHoldingCost DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: data-holding-costs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DataHoldingCost DTOs
 *
 * DDD: Application DTOs for DataHoldingCost use cases.
 */

import type { GetDataHoldingCostParams, ListDataHoldingCostsParams, UpsertDataHoldingCostRequestInput } from "@trustkeep/core/data-holding-costs/types";

export type ListDataHoldingCostsInput = ListDataHoldingCostsParams;

export type UpsertDataHoldingCostInput = UpsertDataHoldingCostRequestInput;

export type GetDataHoldingCostInput = GetDataHoldingCostParams;

export type ListDataHoldingCostsOutput = {};

export type UpsertDataHoldingCostOutput = {};

export type GetDataHoldingCostOutput = {};
