/**
 * MonetizationProposal Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monetization-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { MonetizationProposalEntity } from "@trustkeep/core/monetization-gates/models/index.js";
import { monetizationGatesSchemas } from "@trustkeep/core/monetization-gates";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "mnz";

export function createMonetizationProposal(overrides: Partial<MonetizationProposalEntity> = {}) {
  const raw = {
    id: overrides.id ?? `mnz_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    involvesThirdPartyShare: overrides.involvesThirdPartyShare ?? faker.datatype.boolean(),
    journeyId: overrides.journeyId ?? `jny_${ulid().toLowerCase()}`,
    status: overrides.status ?? "submitted",
    valueProposition: overrides.valueProposition ?? faker.lorem.word(),
    ...overrides,
  };

  return monetizationGatesSchemas.MonetizationProposal.parse(raw);
}

export function monetizationProposalBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createMonetizationProposal(overrides));
}
