/**
 * ExecuteUpdatePlatformRisk - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: platform-risks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpdatePlatformRisk Use Case
 *
 * DDD: Application use case for update PlatformRisk.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpdatePlatformRiskInput, UpdatePlatformRiskOutput } from "../dto/platform-risk.dto";
import type { ExecutionContextService, IdGeneratorService } from "@trustkeep/services/_shared/index.js";
import type { PlatformRiskRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteUpdatePlatformRisk {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly platformRisk: PlatformRiskRepository
  ) {}

  async execute(input: UpdatePlatformRiskInput): Promise<UpdatePlatformRiskOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prkId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).id) {
      throw new ValidationError("id is required");
    }
    const idValue = (input as any).id;
    // No get/list operation for this resource - call update directly
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.platformRisk.updatePlatformRisk({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as UpdatePlatformRiskOutput;
  }
}
