/**
 * ExecuteGetPlatformRisk - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: platform-risks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetPlatformRisk Use Case
 *
 * DDD: Application use case for get PlatformRisk.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetPlatformRiskInput, GetPlatformRiskOutput } from "../dto/platform-risk.dto";
import type { ExecutionContextService, IdGeneratorService } from "@trustkeep/services/_shared/index.js";
import type { PlatformRiskRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetPlatformRisk {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly platformRisk: PlatformRiskRepository
  ) {}

  async execute(input: GetPlatformRiskInput): Promise<GetPlatformRiskOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prkId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).riskId) {
      throw new ValidationError("riskId is required");
    }
    const riskId = (input as any).riskId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.platformRisk.getPlatformRisk({ riskId: riskId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${riskId}`);
    }

    return entity as GetPlatformRiskOutput;
  }
}
