/**
 * GateDecisionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monetization-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * GateDecisionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements GateDecisionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  GateDecisionRepository,
} from "@trustkeep/services/monetization-gates";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { GateDecisionRepositoryDdb } from "./gate-decision-repository.ddb.js";

/**
 * GateDecisionRepositoryAdapter
 *
 * Implements GateDecisionRepository port for infrastructure layer.
 */
export class GateDecisionRepositoryAdapter implements GateDecisionRepository {
  private readonly ddb: GateDecisionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new GateDecisionRepositoryDdb(this.dynamoClient);
  }

  async decideMonetizationGate(input: Parameters<GateDecisionRepository['decideMonetizationGate']>[0]): Promise<Awaited<ReturnType<GateDecisionRepository['decideMonetizationGate']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.decideMonetizationGate(input);
  }
}
