/**
 * PlatformRisks Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: platform-risks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const createPlatformRisk_Body = z
  .object({
    title: z.string().min(1).max(200),
    description: z.string().max(2000).optional(),
    severity: z.enum(['low', 'medium', 'high', 'critical']),
    owner: z.string().min(1).max(120),
    status: z
      .enum(['monitored_clear', 'watch', 'escalate', 'mitigated'])
      .optional(),
    linkedJourneyId: z
      .string()
      .regex(/^jny_[0-9A-HJKMNP-TV-Z]{26}$/)
      .optional(),
  })
  .passthrough();
const updatePlatformRisk_Body = z
  .object({
    title: z.string().min(1).max(200),
    description: z.string().max(2000),
    status: z.enum(['monitored_clear', 'watch', 'escalate', 'mitigated']),
    severity: z.enum(['low', 'medium', 'high', 'critical']),
    owner: z.string().min(1).max(120),
    mitigationNotes: z.string().max(2000),
    linkedJourneyId: z.string().regex(/^jny_[0-9A-HJKMNP-TV-Z]{26}$/),
  })
  .partial()
  .passthrough();

export const schemas: any = {
  createPlatformRisk_Body,
  updatePlatformRisk_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/platform-risks',
    alias: 'listPlatformRisks',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(200).optional().default(50),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  id: z.string().regex(/^prk_[0-9A-HJKMNP-TV-Z]{26}$/),
                  title: z.string().min(1).max(200),
                  description: z.string().max(2000).optional(),
                  status: z.enum([
                    'monitored_clear',
                    'watch',
                    'escalate',
                    'mitigated',
                  ]),
                  severity: z.enum(['low', 'medium', 'high', 'critical']),
                  owner: z.string().min(1).max(120),
                  mitigationNotes: z.string().max(2000).optional(),
                  linkedJourneyId: z
                    .string()
                    .regex(/^jny_[0-9A-HJKMNP-TV-Z]{26}$/)
                    .optional(),
                  createdAt: z.string().datetime({ offset: true }),
                  updatedAt: z.string().datetime({ offset: true }),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/platform-risks',
    alias: 'createPlatformRisk',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: createPlatformRisk_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^prk_[0-9A-HJKMNP-TV-Z]{26}$/),
            title: z.string().min(1).max(200),
            description: z.string().max(2000).optional(),
            status: z.enum([
              'monitored_clear',
              'watch',
              'escalate',
              'mitigated',
            ]),
            severity: z.enum(['low', 'medium', 'high', 'critical']),
            owner: z.string().min(1).max(120),
            mitigationNotes: z.string().max(2000).optional(),
            linkedJourneyId: z
              .string()
              .regex(/^jny_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/platform-risks/:riskId',
    alias: 'getPlatformRisk',
    requestFormat: 'json',
    parameters: [
      {
        name: 'riskId',
        type: 'Path',
        schema: z.string().regex(/^prk_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^prk_[0-9A-HJKMNP-TV-Z]{26}$/),
            title: z.string().min(1).max(200),
            description: z.string().max(2000).optional(),
            status: z.enum([
              'monitored_clear',
              'watch',
              'escalate',
              'mitigated',
            ]),
            severity: z.enum(['low', 'medium', 'high', 'critical']),
            owner: z.string().min(1).max(120),
            mitigationNotes: z.string().max(2000).optional(),
            linkedJourneyId: z
              .string()
              .regex(/^jny_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'patch',
    path: '/v1/platform-risks/:riskId',
    alias: 'updatePlatformRisk',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: updatePlatformRisk_Body,
      },
      {
        name: 'riskId',
        type: 'Path',
        schema: z.string().regex(/^prk_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^prk_[0-9A-HJKMNP-TV-Z]{26}$/),
            title: z.string().min(1).max(200),
            description: z.string().max(2000).optional(),
            status: z.enum([
              'monitored_clear',
              'watch',
              'escalate',
              'mitigated',
            ]),
            severity: z.enum(['low', 'medium', 'high', 'critical']),
            owner: z.string().min(1).max(120),
            mitigationNotes: z.string().max(2000).optional(),
            linkedJourneyId: z
              .string()
              .regex(/^jny_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
