/**
 * Handlers for DataHoldingCost
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: data-holding-costs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { DataHoldingCostsDomainModule } from "../dependencies/data-holding-costs-ddd.dependencies.js";
import type { GetDataHoldingCostInput, ListDataHoldingCostsInput, UpsertDataHoldingCostInput } from "@trustkeep/services/data-holding-costs";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/data-holding-costs
 * Operation: listDataHoldingCosts
 */
export async function listDataHoldingCosts(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: DataHoldingCostsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListDataHoldingCostsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.dataHoldingCosts.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/data-holding-costs
 * Operation: upsertDataHoldingCost
 */
export async function upsertDataHoldingCost(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: DataHoldingCostsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpsertDataHoldingCostInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.dataHoldingCosts.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for GET /v1/data-holding-costs/{costId}
 * Operation: getDataHoldingCost
 */
export async function getDataHoldingCost(
  request: FastifyRequest<{ Params: { costId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: DataHoldingCostsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetDataHoldingCostInput = {
    costId: request.params.costId,
  };
  const result = await deps.useCases.dataHoldingCosts.get.execute(input);
  return reply.code(200).send(result);
}


