/**
 * JourneyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: journeys
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * JourneyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements JourneyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  JourneyRepository,
} from "@trustkeep/services/journeys";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { JourneyRepositoryDdb } from "./journey-repository.ddb.js";

/**
 * JourneyRepositoryAdapter
 *
 * Implements JourneyRepository port for infrastructure layer.
 */
export class JourneyRepositoryAdapter implements JourneyRepository {
  private readonly ddb: JourneyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new JourneyRepositoryDdb(this.dynamoClient);
  }

  async listJourneys(input: Parameters<JourneyRepository['listJourneys']>[0]): Promise<Awaited<ReturnType<JourneyRepository['listJourneys']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listJourneys(input);
  }

  async createJourney(input: Parameters<JourneyRepository['createJourney']>[0]): Promise<Awaited<ReturnType<JourneyRepository['createJourney']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createJourney(input);
  }

  async getJourney(input: Parameters<JourneyRepository['getJourney']>[0]): Promise<Awaited<ReturnType<JourneyRepository['getJourney']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getJourney(input);
  }

  async updateJourney(input: Parameters<JourneyRepository['updateJourney']>[0]): Promise<Awaited<ReturnType<JourneyRepository['updateJourney']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateJourney(input);
  }
}
