/**
 * Repository interface for Journey
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: journeys
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateUpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  JourneyEntity
} from "../models/journey.entity.js";
import type {
  ListJourneysParams,
  Journey,
  UpdateJourneyRequestInput
} from "../types/index.js";
/**
 * JourneyRepository Interface
 */
export interface JourneyRepository extends CreateUpdateReadRepository<JourneyEntity, Journey, UpdateJourneyRequestInput, string, ListJourneysParams> {

}
