/**
 * GetBoardExport DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: board-exports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetBoardExportParams } from "@trustkeep/core/board-exports";

export function createGetBoardExportRequest(overrides: Partial<GetBoardExportParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
