/**
 * GetDataHoldingCost DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: data-holding-costs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetDataHoldingCostParams } from "@trustkeep/core/data-holding-costs";

export function createGetDataHoldingCostRequest(overrides: Partial<GetDataHoldingCostParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
