/**
 * Repository interface for GateDecision
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: monetization-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  GateDecisionEntity
} from "../models/gate-decision.entity.js";
import type {
  GateDecision
} from "../types/index.js";
/**
 * GateDecisionRepository Interface
 */
export interface GateDecisionRepository extends CreateReadRepository<GateDecisionEntity, GateDecision, string, Record<string, never>> {

}
