/**
 * Repository interface for MonetizationProposal
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: monetization-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  MonetizationProposalEntity
} from "../models/monetization-proposal.entity.js";
import type {
  ListMonetizationProposalsParams,
  MonetizationProposal
} from "../types/index.js";
/**
 * MonetizationProposalRepository Interface
 */
export interface MonetizationProposalRepository extends CreateReadRepository<MonetizationProposalEntity, MonetizationProposal, string, ListMonetizationProposalsParams> {

}
