/**
 * Repository interface for TrustScore
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: trust-scores
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  TrustScoreEntity
} from "../models/trust-score.entity.js";
import type {
  ListTrustScoresParams
} from "../types/index.js";
/**
 * TrustScoreRepository Interface
 */
export interface TrustScoreRepository extends ReadRepository<TrustScoreEntity, string, ListTrustScoresParams> {

}
