/**
 * BoardExport Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: board-exports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { BoardExportEntity } from "@trustkeep/core/board-exports/models/index.js";
import { boardExportsSchemas } from "@trustkeep/core/board-exports";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "bxp";

export function createBoardExport(overrides: Partial<BoardExportEntity> = {}) {
  const raw = {
    id: overrides.id ?? `bxp_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    periodLabel: overrides.periodLabel ?? faker.lorem.word(),
    status: overrides.status ?? "pending",
    ...overrides,
  };

  return boardExportsSchemas.BoardExport.parse(raw);
}

export function boardExportBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createBoardExport(overrides));
}
