/**
 * CreatePlatformRisk handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: platform-risks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createPlatformRisk } from "@trustkeep/api-server/domains/platform-risks/handlers";
import type { PlatformRisksDDDDependencies } from "@trustkeep/api-server/domains/platform-risks";
import { createPlatformRisk as createPlatformRiskEntity } from "@trustkeep/factories/platform-risks";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@trustkeep/tests/shared";
import { PLATFORMRISKS_USE_CASES } from "../__factories__/use-cases.js";

describe("CreatePlatformRisk", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: PlatformRisksDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<PlatformRisksDDDDependencies>(
      PLATFORMRISKS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createPlatformRiskEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreatePlatformRisk, "execute").mockResolvedValue(useCaseResult);

    await createPlatformRisk(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreatePlatformRisk.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
