/**
 * GetPlatformRisk handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: platform-risks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getPlatformRisk } from "@trustkeep/api-server/domains/platform-risks/handlers";
import type { PlatformRisksDDDDependencies } from "@trustkeep/api-server/domains/platform-risks";
import { createPlatformRisk as createPlatformRiskEntity } from "@trustkeep/factories/platform-risks";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@trustkeep/tests/shared";
import { PLATFORMRISKS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetPlatformRisk", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: PlatformRisksDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<PlatformRisksDDDDependencies>(
      PLATFORMRISKS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createPlatformRiskEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetPlatformRisk, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { riskId: entity.id };

    await getPlatformRisk(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetPlatformRisk.execute).toHaveBeenCalledWith(expect.objectContaining({ riskId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { riskId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetPlatformRisk, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getPlatformRisk(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
