/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: platform-risks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./create-platform-risk.handler.test.js";
export * from "./get-platform-risk.handler.test.js";
export * from "./list-platform-risks.handler.test.js";
export * from "./update-platform-risk.handler.test.js";
