/**
 * PlatformRisk Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: platform-risks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { PlatformRiskEntity } from "@trustkeep/core/platform-risks/models/index.js";
import { platformRisksSchemas } from "@trustkeep/core/platform-risks";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "prk";

export function createPlatformRisk(overrides: Partial<PlatformRiskEntity> = {}) {
  const raw = {
    id: overrides.id ?? `prk_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    owner: overrides.owner ?? faker.lorem.word(),
    severity: overrides.severity ?? "low",
    status: overrides.status ?? "monitored_clear",
    title: overrides.title ?? faker.lorem.sentence(),
    ...overrides,
  };

  return platformRisksSchemas.PlatformRisk.parse(raw);
}

export function platformRiskBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createPlatformRisk(overrides));
}
