/**
 * Routes for PlatformRisk
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: platform-risks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createPlatformRisk, getPlatformRisk, listPlatformRisks, updatePlatformRisk } from "../handlers/platform-risk.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function platformRiskRoutes(fastify: FastifyInstance) {
  // POST /v1/platform-risks (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/platform-risks",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPlatformRisksDependenciesForRequest();
        await createPlatformRisk(request, reply, deps);
      });
    }
  );


  // GET /v1/platform-risks (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/platform-risks",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPlatformRisksDependenciesForRequest();
        await listPlatformRisks(request, reply, deps);
      });
    }
  );


  // GET /v1/platform-risks/{riskId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/platform-risks/:riskId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { riskId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPlatformRisksDependenciesForRequest();
        await getPlatformRisk(request, reply, deps);
      });
    }
  );


  // PATCH /v1/platform-risks/{riskId} (unscoped; scope set for security middleware)
  fastify.patch(
    "/v1/platform-risks/:riskId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { riskId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPlatformRisksDependenciesForRequest();
        await updatePlatformRisk(request, reply, deps);
      });
    }
  );


}
