/**
 * OpenBreachIncident handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breach-playbooks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { openBreachIncident } from "@trustkeep/api-server/domains/breach-playbooks/handlers";
import type { BreachPlaybooksDDDDependencies } from "@trustkeep/api-server/domains/breach-playbooks";
import { createBreachIncident as createBreachIncidentEntity } from "@trustkeep/factories/breach-playbooks";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@trustkeep/tests/shared";
import { BREACHPLAYBOOKS_USE_CASES } from "../__factories__/use-cases.js";

describe("OpenBreachIncident", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: BreachPlaybooksDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<BreachPlaybooksDDDDependencies>(
      BREACHPLAYBOOKS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createBreachIncidentEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeOpenBreachIncident, "execute").mockResolvedValue(useCaseResult);

    await openBreachIncident(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeOpenBreachIncident.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
