/**
 * GetDataHoldingCost handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: data-holding-costs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getDataHoldingCost } from "@trustkeep/api-server/domains/data-holding-costs/handlers";
import type { DataHoldingCostsDDDDependencies } from "@trustkeep/api-server/domains/data-holding-costs";
import { createDataHoldingCost as createDataHoldingCostEntity } from "@trustkeep/factories/data-holding-costs";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@trustkeep/tests/shared";
import { DATAHOLDINGCOSTS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetDataHoldingCost", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: DataHoldingCostsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<DataHoldingCostsDDDDependencies>(
      DATAHOLDINGCOSTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createDataHoldingCostEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetDataHoldingCost, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { costId: entity.id };

    await getDataHoldingCost(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetDataHoldingCost.execute).toHaveBeenCalledWith(expect.objectContaining({ costId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { costId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetDataHoldingCost, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getDataHoldingCost(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
