/**
 * UpsertDataHoldingCost handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: data-holding-costs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { upsertDataHoldingCost } from "@trustkeep/api-server/domains/data-holding-costs/handlers";
import type { DataHoldingCostsDDDDependencies } from "@trustkeep/api-server/domains/data-holding-costs";
import { createDataHoldingCost as createDataHoldingCostEntity } from "@trustkeep/factories/data-holding-costs";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@trustkeep/tests/shared";
import { DATAHOLDINGCOSTS_USE_CASES } from "../__factories__/use-cases.js";

describe("UpsertDataHoldingCost", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: DataHoldingCostsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<DataHoldingCostsDDDDependencies>(
      DATAHOLDINGCOSTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createDataHoldingCostEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeUpsertDataHoldingCost, "execute").mockResolvedValue(useCaseResult);

    await upsertDataHoldingCost(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeUpsertDataHoldingCost.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
