/**
 * GetDecisionLog handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decision-logs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getDecisionLog } from "@trustkeep/api-server/domains/decision-logs/handlers";
import type { DecisionLogsDDDDependencies } from "@trustkeep/api-server/domains/decision-logs";
import { createDecisionLog as createDecisionLogEntity } from "@trustkeep/factories/decision-logs";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@trustkeep/tests/shared";
import { DECISIONLOGS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetDecisionLog", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: DecisionLogsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<DecisionLogsDDDDependencies>(
      DECISIONLOGS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createDecisionLogEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetDecisionLog, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { decisionId: entity.id };

    await getDecisionLog(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetDecisionLog.execute).toHaveBeenCalledWith(expect.objectContaining({ decisionId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { decisionId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetDecisionLog, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getDecisionLog(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
