/**
 * ListDecisionLogs handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decision-logs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listDecisionLogs } from "@trustkeep/api-server/domains/decision-logs/handlers";
import type { DecisionLogsDDDDependencies } from "@trustkeep/api-server/domains/decision-logs";
import { createDecisionLog as createDecisionLogEntity } from "@trustkeep/factories/decision-logs";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@trustkeep/tests/shared";
import { DECISIONLOGS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListDecisionLogs", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: DecisionLogsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<DecisionLogsDDDDependencies>(
      DECISIONLOGS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createDecisionLogEntity({ orgId }),
      createDecisionLogEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListDecisionLogs, "execute").mockResolvedValue(useCaseResult);

    await listDecisionLogs(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListDecisionLogs.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
