/**
 * DecisionLogs DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decision-logs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DecisionLogs Domain Module - Composition root
 *
 * DDD: Composition root for decision-logs domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  DecisionLogRepositoryAdapter,
} from "@trustkeep/adapters/decision-logs";
import { getIdGeneratorService } from "@trustkeep/adapters";
import type { AdapterDynamoDBClient } from "@trustkeep/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateDecisionLog,
  ExecuteGetDecisionLog,
  ExecuteListDecisionLogs,
} from "@trustkeep/services/decision-logs/usecases";
// Ports (interfaces)
import type {
  DecisionLogRepository,
} from "@trustkeep/services/decision-logs/ports";

export interface DecisionLogsDomainModule {
  repos: {
    decisionLogs: DecisionLogRepository;
  };
  useCases: {
    decisionLogs: {
      create: ExecuteCreateDecisionLog;
      get: ExecuteGetDecisionLog;
      list: ExecuteListDecisionLogs;
    };
  };
}

export function buildDecisionLogsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): DecisionLogsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      decisionLogs?: DecisionLogRepository;
    } = {};

    obj.decisionLogs = new DecisionLogRepositoryAdapter(dynamoClient);
    return {
      decisionLogs: obj.decisionLogs!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    decisionLogs: {
      create: new ExecuteCreateDecisionLog(executionContext, idGenerator, repos.decisionLogs),
      get: new ExecuteGetDecisionLog(executionContext, idGenerator, repos.decisionLogs),
      list: new ExecuteListDecisionLogs(executionContext, idGenerator, repos.decisionLogs),
    },
  };
  return { repos, useCases: useCases as DecisionLogsDomainModule["useCases"] };
}
