/**
 * Journey DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: journeys
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Journey DTOs
 *
 * DDD: Application DTOs for Journey use cases.
 */

import type { CreateJourneyRequestInput, GetJourneyParams, ListJourneysParams, UpdateJourneyParams, UpdateJourneyRequestInput } from "@trustkeep/core/journeys/types";

export type ListJourneysInput = ListJourneysParams;

export type CreateJourneyInput = CreateJourneyRequestInput;

export type GetJourneyInput = GetJourneyParams;

export type UpdateJourneyInput = UpdateJourneyParams & UpdateJourneyRequestInput;

export type ListJourneysOutput = {};

export type CreateJourneyOutput = {};

export type GetJourneyOutput = {};

export type UpdateJourneyOutput = {};
