/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: platform-risks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@trustkeep/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@trustkeep/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@trustkeep/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _boardExports from "./board-exports/index.js";
import * as _breachPlaybooks from "./breach-playbooks/index.js";
import * as _dataHoldingCosts from "./data-holding-costs/index.js";
import * as _decisionLogs from "./decision-logs/index.js";
import * as _identity from "./identity/index.js";
import * as _journeys from "./journeys/index.js";
import * as _monetizationGates from "./monetization-gates/index.js";
import * as _platformRisks from "./platform-risks/index.js";
import * as _trustScores from "./trust-scores/index.js";

// Export as namespaces
export const boardExports = _boardExports;
export const breachPlaybooks = _breachPlaybooks;
export const dataHoldingCosts = _dataHoldingCosts;
export const decisionLogs = _decisionLogs;
export const identity = _identity;
export const journeys = _journeys;
export const monetizationGates = _monetizationGates;
export const platformRisks = _platformRisks;
export const trustScores = _trustScores;
