/**
 * TrustScoreRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust-scores
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TrustScoreRepository Port
 *
 * DDD: Application port for trustscorerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetTrustScoreInput, GetTrustScoreOutput, ListTrustScoresInput, ListTrustScoresOutput } from "../dto/trust-score.dto";
export interface TrustScoreRepository {
  listTrustScores(input: ListTrustScoresInput): Promise<ListTrustScoresOutput>;
  getTrustScore(input: GetTrustScoreInput): Promise<GetTrustScoreOutput>;
}

export type { GetTrustScoreInput, GetTrustScoreOutput, ListTrustScoresInput, ListTrustScoresOutput } from "../dto/trust-score.dto";
