/**
 * TrustScoresComputeRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust-scores
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TrustScoresComputeRepository Port
 *
 * DDD: Application port for trustscorescomputerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ComputeTrustScoreInput, ComputeTrustScoreOutput } from "../dto/trust-scores-compute.dto";
export interface TrustScoresComputeRepository {
  computeTrustScore(input: ComputeTrustScoreInput): Promise<ComputeTrustScoreOutput>;
}

export type { ComputeTrustScoreInput, ComputeTrustScoreOutput } from "../dto/trust-scores-compute.dto";
