/**
 * Models barrel export - All MonetizationGates entities
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monetization-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./gate-decision.entity.js";
export * from "./monetization-proposal.entity.js";
