/**
 * MonetizationProposal Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monetization-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/monetization-gates.openapi.types.js";
import { schemas } from "../schemas/monetization-gates.schemas.js";

/**
 * Entity: MonetizationProposalEntity
 * Description: Represents the MonetizationProposal domain model.
 * Source: schemas.MonetizationProposal
 * Type: Domain Entity (API)
 */
export const MonetizationProposalEntitySchema = schemas.MonetizationProposal;
export type MonetizationProposalEntity = components["schemas"]["MonetizationProposal"];
