/**
 * PlaybookRun Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breach-playbooks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { PlaybookRunEntity } from "@trustkeep/core/breach-playbooks/models/index.js";
import { breachPlaybooksSchemas } from "@trustkeep/core/breach-playbooks";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "brc";

export function createPlaybookRun(overrides: Partial<PlaybookRunEntity> = {}) {
  const raw = {
    id: overrides.id ?? `pbr_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    incidentId: overrides.incidentId ?? `brc_${ulid().toLowerCase()}`,
    playbookKey: overrides.playbookKey ?? "standard_72h",
    startedAt: overrides.startedAt ?? new Date().toISOString(),
    status: overrides.status ?? "running",
    ...overrides,
  };

  return breachPlaybooksSchemas.PlaybookRun.parse(raw);
}

export function playbookRunBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createPlaybookRun(overrides));
}
