/**
 * GateDecisionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monetization-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * GateDecisionRepository Port
 *
 * DDD: Application port for gatedecisionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { DecideMonetizationGateInput, DecideMonetizationGateOutput } from "../dto/gate-decision.dto";
export interface GateDecisionRepository {
  decideMonetizationGate(input: DecideMonetizationGateInput): Promise<DecideMonetizationGateOutput>;
}

export type { DecideMonetizationGateInput, DecideMonetizationGateOutput } from "../dto/gate-decision.dto";
