/**
 * MonetizationProposalRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monetization-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * MonetizationProposalRepository Port
 *
 * DDD: Application port for monetizationproposalrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetMonetizationProposalInput, GetMonetizationProposalOutput, ListMonetizationProposalsInput, ListMonetizationProposalsOutput, SubmitMonetizationProposalInput, SubmitMonetizationProposalOutput } from "../dto/monetization-proposal.dto";
export interface MonetizationProposalRepository {
  listMonetizationProposals(input: ListMonetizationProposalsInput): Promise<ListMonetizationProposalsOutput>;
  submitMonetizationProposal(input: SubmitMonetizationProposalInput): Promise<SubmitMonetizationProposalOutput>;
  getMonetizationProposal(input: GetMonetizationProposalInput): Promise<GetMonetizationProposalOutput>;
}

export type { GetMonetizationProposalInput, GetMonetizationProposalOutput, ListMonetizationProposalsInput, ListMonetizationProposalsOutput, SubmitMonetizationProposalInput, SubmitMonetizationProposalOutput } from "../dto/monetization-proposal.dto";
