/**
 * Repository interface for BreachIncident
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: breach-playbooks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  BreachIncidentEntity
} from "../models/breach-incident.entity.js";
import type {
  ListBreachIncidentsParams,
  BreachIncident
} from "../types/index.js";
/**
 * BreachIncidentRepository Interface
 */
export interface BreachIncidentRepository extends CreateReadRepository<BreachIncidentEntity, BreachIncident, string, ListBreachIncidentsParams> {

}
