/**
 * BreachIncident Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breach-playbooks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/breach-playbooks.openapi.types.js";
import { schemas } from "../schemas/breach-playbooks.schemas.js";

/**
 * Entity: BreachIncidentEntity
 * Description: Represents the BreachIncident domain model.
 * Source: schemas.BreachIncident
 * Type: Domain Entity (API)
 */
export const BreachIncidentEntitySchema = schemas.BreachIncident;
export type BreachIncidentEntity = components["schemas"]["BreachIncident"];
