/**
 * PlaybookRun Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breach-playbooks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/breach-playbooks.openapi.types.js";
import { schemas } from "../schemas/breach-playbooks.schemas.js";

/**
 * Entity: PlaybookRunEntity
 * Description: Represents the PlaybookRun domain model.
 * Source: schemas.PlaybookRun
 * Type: Domain Entity (API)
 */
export const PlaybookRunEntitySchema = schemas.PlaybookRun;
export type PlaybookRunEntity = components["schemas"]["PlaybookRun"];
