/**
 * GetBreachIncident DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breach-playbooks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetBreachIncidentParams } from "@trustkeep/core/breach-playbooks";

export function createGetBreachIncidentRequest(overrides: Partial<GetBreachIncidentParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
