/**
 * ExecuteGetDecisionLog - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decision-logs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetDecisionLog Use Case
 *
 * DDD: Application use case for get DecisionLog.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetDecisionLogInput, GetDecisionLogOutput } from "../dto/decision-log.dto";
import type { ExecutionContextService, IdGeneratorService } from "@trustkeep/services/_shared/index.js";
import type { DecisionLogRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetDecisionLog {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly decisionLog: DecisionLogRepository
  ) {}

  async execute(input: GetDecisionLogInput): Promise<GetDecisionLogOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dlgId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).decisionId) {
      throw new ValidationError("decisionId is required");
    }
    const decisionId = (input as any).decisionId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.decisionLog.getDecisionLog({ decisionId: decisionId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${decisionId}`);
    }

    return entity as GetDecisionLogOutput;
  }
}
