/**
 * ListJourney DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: journeys
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListJourneysParams } from "@trustkeep/core/journeys";

export function createListJourneyRequest(overrides: Partial<ListJourneysParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
