/**
 * ExecuteCreateJourney - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: journeys
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateJourney Use Case
 *
 * DDD: Application use case for create Journey.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateJourneyInput, CreateJourneyOutput } from "../dto/journey.dto";
import type { ExecutionContextService, IdGeneratorService } from "@trustkeep/services/_shared/index.js";
import type { JourneyRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateJourney {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly journey: JourneyRepository
  ) {}

  async execute(input: CreateJourneyInput): Promise<CreateJourneyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.jnyId();

    // All field names extracted from OpenAPI spec: journeyKey, name, trustThreshold, valuePropositions
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.name) {
      throw new ValidationError("name is required");
    }
    if (!input.journeyKey) {
      throw new ValidationError("journeyKey is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (journeys domain)
    const entityId = this.idGenerator.jnyId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.journey.createJourney({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateJourneyOutput;
  }
}
