/**
 * ExecuteGetJourney - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: journeys
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetJourney Use Case
 *
 * DDD: Application use case for get Journey.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetJourneyInput, GetJourneyOutput } from "../dto/journey.dto";
import type { ExecutionContextService, IdGeneratorService } from "@trustkeep/services/_shared/index.js";
import type { JourneyRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetJourney {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly journey: JourneyRepository
  ) {}

  async execute(input: GetJourneyInput): Promise<GetJourneyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.jnyId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).journeyId) {
      throw new ValidationError("journeyId is required");
    }
    const journeyId = (input as any).journeyId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.journey.getJourney({ journeyId: journeyId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${journeyId}`);
    }

    return entity as GetJourneyOutput;
  }
}
