/**
 * DataHoldingCostRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: data-holding-costs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DataHoldingCostRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DataHoldingCostRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DataHoldingCostRepository,
} from "@trustkeep/services/data-holding-costs";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DataHoldingCostRepositoryDdb } from "./data-holding-cost-repository.ddb.js";

/**
 * DataHoldingCostRepositoryAdapter
 *
 * Implements DataHoldingCostRepository port for infrastructure layer.
 */
export class DataHoldingCostRepositoryAdapter implements DataHoldingCostRepository {
  private readonly ddb: DataHoldingCostRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DataHoldingCostRepositoryDdb(this.dynamoClient);
  }

  async listDataHoldingCosts(input: Parameters<DataHoldingCostRepository['listDataHoldingCosts']>[0]): Promise<Awaited<ReturnType<DataHoldingCostRepository['listDataHoldingCosts']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listDataHoldingCosts(input);
  }

  async upsertDataHoldingCost(input: Parameters<DataHoldingCostRepository['upsertDataHoldingCost']>[0]): Promise<Awaited<ReturnType<DataHoldingCostRepository['upsertDataHoldingCost']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.upsertDataHoldingCost(input);
  }

  async getDataHoldingCost(input: Parameters<DataHoldingCostRepository['getDataHoldingCost']>[0]): Promise<Awaited<ReturnType<DataHoldingCostRepository['getDataHoldingCost']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getDataHoldingCost(input);
  }
}
