/**
 * ExecuteComputeTrustScore - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust-scores
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteComputeTrustScore Use Case
 *
 * DDD: Application use case for get TrustScoresCompute.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ComputeTrustScoreInput, ComputeTrustScoreOutput } from "../dto/trust-scores-compute.dto";
import type { ExecutionContextService, IdGeneratorService } from "@trustkeep/services/_shared/index.js";
import type { TrustScoresComputeRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteComputeTrustScore {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly trustScoresCompute: TrustScoresComputeRepository
  ) {}

  async execute(input: ComputeTrustScoreInput): Promise<ComputeTrustScoreOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.trsId();

    // All field names extracted from OpenAPI spec: complaintProxyRate, optInRate, periodLabel, revokeRate
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).journeyId) {
      throw new ValidationError("journeyId is required");
    }
    const journeyId = (input as any).journeyId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.trustScoresCompute.computeTrustScore({ journeyId: journeyId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${journeyId}`);
    }

    return entity as ComputeTrustScoreOutput;
  }
}
