/**
 * ExecuteGetTrustScore - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust-scores
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetTrustScore Use Case
 *
 * DDD: Application use case for get TrustScore.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetTrustScoreInput, GetTrustScoreOutput } from "../dto/trust-score.dto";
import type { ExecutionContextService, IdGeneratorService } from "@trustkeep/services/_shared/index.js";
import type { TrustScoreRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetTrustScore {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly trustScore: TrustScoreRepository
  ) {}

  async execute(input: GetTrustScoreInput): Promise<GetTrustScoreOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.trsId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).trustScoreId) {
      throw new ValidationError("trustScoreId is required");
    }
    const trustscoreId = (input as any).trustScoreId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.trustScore.getTrustScore({ trustScoreId: trustscoreId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${trustscoreId}`);
    }

    return entity as GetTrustScoreOutput;
  }
}
