/**
 * GetMonetizationProposal handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monetization-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getMonetizationProposal } from "@trustkeep/api-server/domains/monetization-gates/handlers";
import type { MonetizationGatesDDDDependencies } from "@trustkeep/api-server/domains/monetization-gates";
import { createMonetizationProposal as createMonetizationProposalEntity } from "@trustkeep/factories/monetization-gates";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@trustkeep/tests/shared";
import { MONETIZATIONGATES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetMonetizationProposal", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: MonetizationGatesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<MonetizationGatesDDDDependencies>(
      MONETIZATIONGATES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createMonetizationProposalEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetMonetizationProposal, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { proposalId: entity.id };

    await getMonetizationProposal(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetMonetizationProposal.execute).toHaveBeenCalledWith(expect.objectContaining({ proposalId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { proposalId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetMonetizationProposal, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getMonetizationProposal(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
