/**
 * ListMonetizationProposals handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monetization-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listMonetizationProposals } from "@trustkeep/api-server/domains/monetization-gates/handlers";
import type { MonetizationGatesDDDDependencies } from "@trustkeep/api-server/domains/monetization-gates";
import { createMonetizationProposal as createMonetizationProposalEntity } from "@trustkeep/factories/monetization-gates";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@trustkeep/tests/shared";
import { MONETIZATIONGATES_USE_CASES } from "../__factories__/use-cases.js";

describe("ListMonetizationProposals", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: MonetizationGatesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<MonetizationGatesDDDDependencies>(
      MONETIZATIONGATES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createMonetizationProposalEntity({ orgId }),
      createMonetizationProposalEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListMonetizationProposals, "execute").mockResolvedValue(useCaseResult);

    await listMonetizationProposals(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListMonetizationProposals.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
