/**
 * TrustDeltumRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breach-playbooks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TrustDeltumRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements TrustDeltumRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  TrustDeltumRepository,
} from "@trustkeep/services/breach-playbooks";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { TrustDeltumRepositoryDdb } from "./trust-deltum-repository.ddb.js";

/**
 * TrustDeltumRepositoryAdapter
 *
 * Implements TrustDeltumRepository port for infrastructure layer.
 */
export class TrustDeltumRepositoryAdapter implements TrustDeltumRepository {
  private readonly ddb: TrustDeltumRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new TrustDeltumRepositoryDdb(this.dynamoClient);
  }

  async recordPlaybookTrustDelta(input: Parameters<TrustDeltumRepository['recordPlaybookTrustDelta']>[0]): Promise<Awaited<ReturnType<TrustDeltumRepository['recordPlaybookTrustDelta']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.recordPlaybookTrustDelta(input);
  }
}
