/**
 * GateDecision DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monetization-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * GateDecision DTOs
 *
 * DDD: Application DTOs for GateDecision use cases.
 */

import type { DecideMonetizationGateParams, DecideMonetizationGateRequestInput } from "@trustkeep/core/monetization-gates/types";

export type DecideMonetizationGateInput = DecideMonetizationGateParams & DecideMonetizationGateRequestInput;

export type DecideMonetizationGateOutput = {};
