/**
 * MonetizationProposal DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monetization-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * MonetizationProposal DTOs
 *
 * DDD: Application DTOs for MonetizationProposal use cases.
 */

import type { GetMonetizationProposalParams, ListMonetizationProposalsParams, SubmitMonetizationProposalRequestInput } from "@trustkeep/core/monetization-gates/types";

export type ListMonetizationProposalsInput = ListMonetizationProposalsParams;

export type SubmitMonetizationProposalInput = SubmitMonetizationProposalRequestInput;

export type GetMonetizationProposalInput = GetMonetizationProposalParams;

export type ListMonetizationProposalsOutput = {};

export type SubmitMonetizationProposalOutput = {};

export type GetMonetizationProposalOutput = {};
