/**
 * DecisionLogRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decision-logs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DecisionLogRepository Port
 *
 * DDD: Application port for decisionlogrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateDecisionLogInput, CreateDecisionLogOutput, GetDecisionLogInput, GetDecisionLogOutput, ListDecisionLogsInput, ListDecisionLogsOutput } from "../dto/decision-log.dto";
export interface DecisionLogRepository {
  listDecisionLogs(input: ListDecisionLogsInput): Promise<ListDecisionLogsOutput>;
  createDecisionLog(input: CreateDecisionLogInput): Promise<CreateDecisionLogOutput>;
  getDecisionLog(input: GetDecisionLogInput): Promise<GetDecisionLogOutput>;
}

export type { CreateDecisionLogInput, CreateDecisionLogOutput, GetDecisionLogInput, GetDecisionLogOutput, ListDecisionLogsInput, ListDecisionLogsOutput } from "../dto/decision-log.dto";
