/**
 * Routes for Journey
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: journeys
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createJourney, getJourney, listJourneys, updateJourney } from "../handlers/journey.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function journeyRoutes(fastify: FastifyInstance) {
  // POST /v1/journeys (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/journeys",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getJourneysDependenciesForRequest();
        await createJourney(request, reply, deps);
      });
    }
  );


  // GET /v1/journeys (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/journeys",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getJourneysDependenciesForRequest();
        await listJourneys(request, reply, deps);
      });
    }
  );


  // GET /v1/journeys/{journeyId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/journeys/:journeyId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { journeyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getJourneysDependenciesForRequest();
        await getJourney(request, reply, deps);
      });
    }
  );


  // PATCH /v1/journeys/{journeyId} (unscoped; scope set for security middleware)
  fastify.patch(
    "/v1/journeys/:journeyId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { journeyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getJourneysDependenciesForRequest();
        await updateJourney(request, reply, deps);
      });
    }
  );


}
