/**
 * GateDecision Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monetization-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GateDecisionEntity } from "@trustkeep/core/monetization-gates/models/index.js";
import { monetizationGatesSchemas } from "@trustkeep/core/monetization-gates";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "mnz";

export function createGateDecision(overrides: Partial<GateDecisionEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    ...overrides,
  };

  return monetizationGatesSchemas.GateDecision.parse(raw);
}

export function gateDecisionBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createGateDecision(overrides));
}
