/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: journeys
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Journeys Domain Use Cases
 * 
 * List of all use case names for the journeys domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const JOURNEYS_USE_CASES = [
  "executeCreateJourney",
  "executeGetJourney",
  "executeListJourneys",
  "executeUpdateJourney"
] as const;
