/**
 * PlaybookRunRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breach-playbooks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PlaybookRunRepository Port
 *
 * DDD: Application port for playbookrunrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListPlaybookRunsInput, ListPlaybookRunsOutput, StartPlaybookRunInput, StartPlaybookRunOutput } from "../dto/playbook-run.dto";
export interface PlaybookRunRepository {
  listPlaybookRuns(input: ListPlaybookRunsInput): Promise<ListPlaybookRunsOutput>;
  startPlaybookRun(input: StartPlaybookRunInput): Promise<StartPlaybookRunOutput>;
}

export type { ListPlaybookRunsInput, ListPlaybookRunsOutput, StartPlaybookRunInput, StartPlaybookRunOutput } from "../dto/playbook-run.dto";
