/**
 * TrustDeltumRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: breach-playbooks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TrustDeltumRepository Port
 *
 * DDD: Application port for trustdeltumrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { RecordPlaybookTrustDeltaInput, RecordPlaybookTrustDeltaOutput } from "../dto/trust-deltum.dto";
export interface TrustDeltumRepository {
  recordPlaybookTrustDelta(input: RecordPlaybookTrustDeltaInput): Promise<RecordPlaybookTrustDeltaOutput>;
}

export type { RecordPlaybookTrustDeltaInput, RecordPlaybookTrustDeltaOutput } from "../dto/trust-deltum.dto";
