/**
 * ExecuteGetBoardExport - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: board-exports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetBoardExport Use Case
 *
 * DDD: Application use case for get BoardExport.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetBoardExportInput, GetBoardExportOutput } from "../dto/board-export.dto";
import type { ExecutionContextService, IdGeneratorService } from "@trustkeep/services/_shared/index.js";
import type { BoardExportRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetBoardExport {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly boardExport: BoardExportRepository
  ) {}

  async execute(input: GetBoardExportInput): Promise<GetBoardExportOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.bxpId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).exportId) {
      throw new ValidationError("exportId is required");
    }
    const exportId = (input as any).exportId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.boardExport.getBoardExport({ exportId: exportId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${exportId}`);
    }

    return entity as GetBoardExportOutput;
  }
}
