/**
 * ExecuteListBoardExports - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: board-exports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListBoardExports Use Case
 *
 * DDD: Application use case for list BoardExport.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListBoardExportsInput, ListBoardExportsOutput } from "../dto/board-export.dto";
import type { ExecutionContextService, IdGeneratorService } from "@trustkeep/services/_shared/index.js";
import type { BoardExportRepository } from "../ports";

export class ExecuteListBoardExports {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly boardExport: BoardExportRepository
  ) {}

  async execute(input: ListBoardExportsInput): Promise<ListBoardExportsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.bxpId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.boardExport.listBoardExports({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListBoardExportsOutput;
  }
}
