/**
 * ExecuteCreateBoardExport - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: board-exports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateBoardExport Use Case
 *
 * DDD: Application use case for create BoardExport.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateBoardExportInput, CreateBoardExportOutput } from "../dto/board-export.dto";
import type { ExecutionContextService, IdGeneratorService } from "@trustkeep/services/_shared/index.js";
import type { BoardExportRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateBoardExport {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly boardExport: BoardExportRepository
  ) {}

  async execute(input: CreateBoardExportInput): Promise<CreateBoardExportOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.bxpId();

    // All field names extracted from OpenAPI spec: includeBreachRecovery, includeGates, includeHoldingCosts, includePlatformRisks, journeyIds, periodLabel
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.periodLabel) {
      throw new ValidationError("periodLabel is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (board-exports domain)
    const entityId = this.idGenerator.bxpId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.boardExport.createBoardExport({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateBoardExportOutput;
  }
}
