/**
 * Handlers for GateDecision
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monetization-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { MonetizationGatesDomainModule } from "../dependencies/monetization-gates-ddd.dependencies.js";
import type { DecideMonetizationGateInput } from "@trustkeep/services/monetization-gates";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/monetization-proposals/{proposalId}/gate-decision
 * Operation: decideMonetizationGate
 */
export async function decideMonetizationGate(
  request: FastifyRequest<{ Params: { proposalId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: MonetizationGatesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: DecideMonetizationGateInput = {
    proposalId: request.params.proposalId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.gateDecisions.get.execute(input);
  return reply.code(200).send(result);
}


