/**
 * DecisionLog Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decision-logs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { DecisionLogEntity } from "@trustkeep/core/decision-logs/models/index.js";
import { decisionLogsSchemas } from "@trustkeep/core/decision-logs";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "dlg";

export function createDecisionLog(overrides: Partial<DecisionLogEntity> = {}) {
  const raw = {
    id: overrides.id ?? `dlg_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    category: overrides.category ?? "compliance",
    decidedAt: overrides.decidedAt ?? new Date().toISOString(),
    outcome: overrides.outcome ?? faker.lorem.word(),
    title: overrides.title ?? faker.lorem.sentence(),
    ...overrides,
  };

  return decisionLogsSchemas.DecisionLog.parse(raw);
}

export function decisionLogBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createDecisionLog(overrides));
}
