/**
 * Routes for DataHoldingCost
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: data-holding-costs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getDataHoldingCost, listDataHoldingCosts, upsertDataHoldingCost } from "../handlers/data-holding-cost.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function dataHoldingCostRoutes(fastify: FastifyInstance) {
  // GET /v1/data-holding-costs (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/data-holding-costs",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDataHoldingCostsDependenciesForRequest();
        await listDataHoldingCosts(request, reply, deps);
      });
    }
  );


  // POST /v1/data-holding-costs (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/data-holding-costs",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDataHoldingCostsDependenciesForRequest();
        await upsertDataHoldingCost(request, reply, deps);
      });
    }
  );


  // GET /v1/data-holding-costs/{costId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/data-holding-costs/:costId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { costId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDataHoldingCostsDependenciesForRequest();
        await getDataHoldingCost(request, reply, deps);
      });
    }
  );


}
