/**
 * GetMonetizationProposal DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monetization-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetMonetizationProposalParams } from "@trustkeep/core/monetization-gates";

export function createGetMonetizationProposalRequest(overrides: Partial<GetMonetizationProposalParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
