/**
 * Repository interface for DecisionLog
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: decision-logs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  DecisionLogEntity
} from "../models/decision-log.entity.js";
import type {
  ListDecisionLogsParams,
  DecisionLog
} from "../types/index.js";
/**
 * DecisionLogRepository Interface
 */
export interface DecisionLogRepository extends CreateReadRepository<DecisionLogEntity, DecisionLog, string, ListDecisionLogsParams> {

}
