/**
 * GetJourney handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: journeys
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getJourney } from "@trustkeep/api-server/domains/journeys/handlers";
import type { JourneysDDDDependencies } from "@trustkeep/api-server/domains/journeys";
import { createJourney as createJourneyEntity } from "@trustkeep/factories/journeys";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@trustkeep/tests/shared";
import { JOURNEYS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetJourney", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: JourneysDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<JourneysDDDDependencies>(
      JOURNEYS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createJourneyEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetJourney, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { journeyId: entity.id };

    await getJourney(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetJourney.execute).toHaveBeenCalledWith(expect.objectContaining({ journeyId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { journeyId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetJourney, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getJourney(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
