/**
 * ListJourneys handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: journeys
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listJourneys } from "@trustkeep/api-server/domains/journeys/handlers";
import type { JourneysDDDDependencies } from "@trustkeep/api-server/domains/journeys";
import { createJourney as createJourneyEntity } from "@trustkeep/factories/journeys";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@trustkeep/tests/shared";
import { JOURNEYS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListJourneys", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: JourneysDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<JourneysDDDDependencies>(
      JOURNEYS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createJourneyEntity({ orgId }),
      createJourneyEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListJourneys, "execute").mockResolvedValue(useCaseResult);

    await listJourneys(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListJourneys.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
