/**
 * TrustScores Schemas - Domain schemas barrel export
 *
 * Generated by Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust-scores
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { schemas } from "../openapi/trust-scores.zod.schema.js";

export { schemas };
